-- Feature 5: Genera Documenti
-- Tables for document templates and generated documents

CREATE TABLE IF NOT EXISTS documenti_sistema (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  club_id       UUID REFERENCES clubs(id) ON DELETE CASCADE,  -- NULL = template di sistema
  categoria     TEXT NOT NULL,   -- dichiarazioni | contratti | privacy | tesseramento | varie
  titolo        TEXT NOT NULL,
  descrizione   TEXT,
  corpo_html    TEXT NOT NULL,   -- HTML con {{placeholder}}
  placeholders  JSONB DEFAULT '[]'::jsonb,  -- array di {chiave, etichetta, tipo}
  is_sistema    BOOLEAN DEFAULT true,
  attivo        BOOLEAN DEFAULT true,
  ordine        INT DEFAULT 0,
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS documenti_generati (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  club_id         UUID REFERENCES clubs(id) ON DELETE CASCADE,
  documento_id    UUID REFERENCES documenti_sistema(id),
  giocatore_id    UUID REFERENCES giocatori(id),
  titolo          TEXT NOT NULL,
  corpo_html      TEXT NOT NULL,
  generato_da     UUID REFERENCES utenti(id),
  generato_il     TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE documenti_sistema DISABLE ROW LEVEL SECURITY;
ALTER TABLE documenti_generati DISABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS documenti_sistema_categoria ON documenti_sistema(categoria);
CREATE INDEX IF NOT EXISTS documenti_generati_club ON documenti_generati(club_id);
CREATE INDEX IF NOT EXISTS documenti_generati_giocatore ON documenti_generati(giocatore_id);

-- Seed: 24 documenti di sistema (club_id = NULL → disponibili per tutti i club)
INSERT INTO documenti_sistema (club_id, categoria, titolo, descrizione, corpo_html, placeholders, is_sistema, ordine) VALUES

-- DICHIARAZIONI (6)
(NULL, 'dichiarazioni', 'Dichiarazione per Modello 730 – Rimborso Spese',
 'Dichiarazione da allegare al 730 per rimborso spese sportive',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:12pt;margin:40px;line-height:1.6;color:#000}h1{font-size:14pt;text-align:center;margin-bottom:6px}h2{font-size:11pt;text-align:center;margin-top:0;font-weight:normal}p{margin:8px 0}.firma{margin-top:40px;display:flex;justify-content:space-between}.data-firma{text-align:right}</style></head><body><h1>{{club_nome}}</h1><h2>{{club_indirizzo}} – C.F. {{club_cf}}</h2><br><h1>DICHIARAZIONE AI FINI DEL MODELLO 730</h1><p>Il/La sottoscritto/a <strong>{{legale_nome}}</strong>, in qualità di <strong>{{legale_ruolo}}</strong> dell''Associazione Sportiva Dilettantistica <strong>{{club_nome}}</strong>, C.F. <strong>{{club_cf}}</strong>,</p><p><strong>DICHIARA</strong></p><p>che il/la Sig./Sig.ra <strong>{{genitore_nome}}</strong> (C.F. <strong>{{genitore_cf}}</strong>), genitore/tutore dell''atleta <strong>{{atleta_nome}}</strong> (C.F. <strong>{{atleta_cf}}</strong>), ha versato nell''anno <strong>{{anno}}</strong> la somma di <strong>€ {{importo}}</strong> a titolo di quota associativa e/o retta di frequenza per la pratica di attività sportiva dilettantistica.</p><p>La presente dichiarazione è rilasciata ai sensi e per gli effetti dell''art. 15, comma 1, lett. i-quinquies del D.P.R. 917/1986 (TUIR) per le detrazioni fiscali previste per le spese sportive dei ragazzi.</p><div class="firma"><div><p>Luogo e data: {{citta}}, {{data}}</p></div><div class="data-firma"><p>Il Legale Rappresentante</p><br><p>________________________</p><p><strong>{{legale_nome}}</strong></p></div></div></body></html>',
 '[{"chiave":"anno","etichetta":"Anno","tipo":"text"},{"chiave":"genitore_nome","etichetta":"Nome genitore","tipo":"text"},{"chiave":"genitore_cf","etichetta":"CF genitore","tipo":"text"},{"chiave":"atleta_nome","etichetta":"Nome atleta","tipo":"text"},{"chiave":"atleta_cf","etichetta":"CF atleta","tipo":"text"},{"chiave":"importo","etichetta":"Importo €","tipo":"text"},{"chiave":"data","etichetta":"Data","tipo":"text"}]'::jsonb,
 true, 1),

(NULL, 'dichiarazioni', 'Dichiarazione di Residenza Sportiva',
 'Dichiarazione di tesseramento e residenza sportiva dell''atleta',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:12pt;margin:40px;line-height:1.6}h1{font-size:14pt;text-align:center}h2{font-size:11pt;text-align:center;font-weight:normal}.firma{margin-top:40px;display:flex;justify-content:space-between}</style></head><body><h1>{{club_nome}}</h1><h2>Affiliata {{federazione}} – Cod. {{figc_codice}}</h2><br><h1>DICHIARAZIONE DI RESIDENZA SPORTIVA</h1><p>Il/La sottoscritto/a <strong>{{legale_nome}}</strong>, Legale Rappresentante dell''ASD <strong>{{club_nome}}</strong>, <strong>DICHIARA</strong> che l''atleta <strong>{{atleta_nome}}</strong>, nato/a il <strong>{{atleta_data_nascita}}</strong>, è regolarmente tesserato/a con la scrivente società per la stagione sportiva <strong>{{stagione}}</strong>, con numero di tessera <strong>{{numero_tessera}}</strong>.</p><p>La presente è rilasciata per gli usi consentiti dalla legge.</p><div class="firma"><div><p>{{citta}}, {{data}}</p></div><div style="text-align:right"><p>Il Legale Rappresentante</p><br><p>________________________</p><p><strong>{{legale_nome}}</strong></p></div></div></body></html>',
 '[{"chiave":"federazione","etichetta":"Federazione","tipo":"text"},{"chiave":"stagione","etichetta":"Stagione sportiva","tipo":"text"},{"chiave":"atleta_nome","etichetta":"Nome atleta","tipo":"text"},{"chiave":"atleta_data_nascita","etichetta":"Data nascita atleta","tipo":"text"},{"chiave":"numero_tessera","etichetta":"Numero tessera","tipo":"text"},{"chiave":"data","etichetta":"Data","tipo":"text"}]'::jsonb,
 true, 2),

(NULL, 'dichiarazioni', 'Dichiarazione Assenza Vincolo',
 'Dichiarazione che l''atleta è privo di vincoli con altre società',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:12pt;margin:40px;line-height:1.6}h1{font-size:14pt;text-align:center}.firma{margin-top:40px;display:flex;justify-content:space-between}</style></head><body><h1>{{club_nome}}</h1><br><h1>DICHIARAZIONE DI ASSENZA VINCOLO</h1><p>Il/La sottoscritto/a <strong>{{legale_nome}}</strong>, Legale Rappresentante della società <strong>{{club_nome}}</strong>, <strong>DICHIARA</strong> che l''atleta <strong>{{atleta_nome}}</strong>, nato/a il <strong>{{atleta_data_nascita}}</strong>, alla data odierna non è vincolato/a ad alcuna altra società sportiva affiliata alla medesima federazione e che nulla osta al suo tesseramento con la scrivente società.</p><div class="firma"><div><p>{{citta}}, {{data}}</p></div><div style="text-align:right"><p>Il Legale Rappresentante</p><br><p>________________________</p></div></div></body></html>',
 '[{"chiave":"atleta_nome","etichetta":"Nome atleta","tipo":"text"},{"chiave":"atleta_data_nascita","etichetta":"Data nascita","tipo":"text"},{"chiave":"data","etichetta":"Data","tipo":"text"}]'::jsonb,
 true, 3),

(NULL, 'dichiarazioni', 'Comunicazione Cambio Allenatore',
 'Comunicazione formale di cambio tecnico alla federazione',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:12pt;margin:40px;line-height:1.6}h1{font-size:13pt;text-align:center}.firma{margin-top:40px}</style></head><body><h1>{{club_nome}} – COMUNICAZIONE UFFICIALE</h1><p>Alla cortese attenzione del Comitato Regionale / Provinciale {{federazione}}</p><p>La scrivente società <strong>{{club_nome}}</strong>, con la presente, comunica ufficialmente che a partire dal <strong>{{data_inizio}}</strong> la conduzione tecnica della squadra <strong>{{nome_squadra}}</strong> (categoria <strong>{{categoria}}</strong>) è affidata al Sig./Sig.ra <strong>{{nuovo_allenatore}}</strong>, titolare di patentino <strong>{{patentino}}</strong> n. <strong>{{num_patentino}}</strong>.</p><p>Si allega copia del patentino e del tesseramento.</p><div class="firma"><p>{{citta}}, {{data}}</p><br><p>Il Presidente: ________________________</p><p><strong>{{legale_nome}}</strong></p></div></body></html>',
 '[{"chiave":"nome_squadra","etichetta":"Nome squadra","tipo":"text"},{"chiave":"categoria","etichetta":"Categoria","tipo":"text"},{"chiave":"nuovo_allenatore","etichetta":"Nuovo allenatore","tipo":"text"},{"chiave":"patentino","etichetta":"Tipo patentino","tipo":"text"},{"chiave":"num_patentino","etichetta":"N. patentino","tipo":"text"},{"chiave":"data_inizio","etichetta":"Data inizio incarico","tipo":"text"},{"chiave":"data","etichetta":"Data comunicazione","tipo":"text"},{"chiave":"federazione","etichetta":"Federazione","tipo":"text"}]'::jsonb,
 true, 4),

(NULL, 'dichiarazioni', 'Richiesta Rimborso Spese Trasferta',
 'Modulo di richiesta rimborso spese per tecnici e collaboratori',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:11pt;margin:40px;line-height:1.6}h1{font-size:13pt;text-align:center}table{width:100%;border-collapse:collapse;margin:16px 0}th,td{border:1px solid #aaa;padding:6px 10px;font-size:11pt}th{background:#f0f0f0}.firma{margin-top:40px;display:flex;justify-content:space-between}</style></head><body><h1>{{club_nome}} – RICHIESTA RIMBORSO SPESE</h1><p><strong>Richiedente:</strong> {{richiedente_nome}} &nbsp;&nbsp; <strong>C.F.:</strong> {{richiedente_cf}}</p><p><strong>Evento/Trasferta:</strong> {{evento}} &nbsp;&nbsp; <strong>Data:</strong> {{data_evento}}</p><table><thead><tr><th>Descrizione</th><th>Km/Importo</th><th>Note</th></tr></thead><tbody><tr><td>Carburante / Rimborso km</td><td>{{km}} km × {{costo_km}} €/km</td><td></td></tr><tr><td>Pedaggi autostrada</td><td>{{pedaggi}} €</td><td></td></tr><tr><td>Vitto</td><td>{{vitto}} €</td><td></td></tr><tr><td>Alloggio</td><td>{{alloggio}} €</td><td></td></tr><tr><td><strong>TOTALE</strong></td><td><strong>{{totale}} €</strong></td><td></td></tr></tbody></table><div class="firma"><div><p>Firma del richiedente</p><br><p>________________________</p></div><div><p>Visto del Presidente</p><br><p>________________________</p></div></div></body></html>',
 '[{"chiave":"richiedente_nome","etichetta":"Nome richiedente","tipo":"text"},{"chiave":"richiedente_cf","etichetta":"CF richiedente","tipo":"text"},{"chiave":"evento","etichetta":"Evento/trasferta","tipo":"text"},{"chiave":"data_evento","etichetta":"Data evento","tipo":"text"},{"chiave":"km","etichetta":"Km percorsi","tipo":"text"},{"chiave":"costo_km","etichetta":"€/km","tipo":"text"},{"chiave":"pedaggi","etichetta":"Pedaggi €","tipo":"text"},{"chiave":"vitto","etichetta":"Vitto €","tipo":"text"},{"chiave":"alloggio","etichetta":"Alloggio €","tipo":"text"},{"chiave":"totale","etichetta":"Totale €","tipo":"text"}]'::jsonb,
 true, 5),

(NULL, 'dichiarazioni', 'Convocazione Assemblea Soci',
 'Lettera di convocazione per assemblea ordinaria/straordinaria',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:12pt;margin:40px;line-height:1.8}h1{font-size:14pt;text-align:center}.firma{margin-top:40px}</style></head><body><h1>{{club_nome}}</h1><br><p>Spett. Socio/a,</p><p>Su incarico del Presidente, La invitiamo a partecipare all''<strong>ASSEMBLEA {{tipo_assemblea}}</strong> dei Soci che si terrà il giorno <strong>{{data}}</strong> alle ore <strong>{{ora}}</strong> presso <strong>{{luogo}}</strong>.</p><p><strong>Ordine del giorno:</strong></p><ol>{{ordine_del_giorno}}</ol><p>In caso di mancanza del numero legale in prima convocazione, la seconda convocazione è fissata per lo stesso giorno alle ore {{ora_seconda_conv}} con identico ordine del giorno.</p><p>La preghiamo di confermare la partecipazione entro il <strong>{{scadenza_conferma}}</strong>.</p><div class="firma"><p>Distinti saluti,</p><br><p>Il Presidente</p><p><strong>{{legale_nome}}</strong></p></div></body></html>',
 '[{"chiave":"tipo_assemblea","etichetta":"Tipo assemblea (ORDINARIA/STRAORDINARIA)","tipo":"text"},{"chiave":"data","etichetta":"Data assemblea","tipo":"text"},{"chiave":"ora","etichetta":"Ora (prima conv.)","tipo":"text"},{"chiave":"ora_seconda_conv","etichetta":"Ora (seconda conv.)","tipo":"text"},{"chiave":"luogo","etichetta":"Luogo","tipo":"text"},{"chiave":"ordine_del_giorno","etichetta":"Ordine del giorno (HTML <li>)","tipo":"textarea"},{"chiave":"scadenza_conferma","etichetta":"Scadenza conferma","tipo":"text"}]'::jsonb,
 true, 6),

-- CONTRATTI (5)
(NULL, 'contratti', 'Contratto Collaborazione Coordinata (Co.Co.Co.) – Allenatore',
 'Contratto di collaborazione coordinata e continuativa per allenatore D.Lgs. 36/2021',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:11pt;margin:40px;line-height:1.7}h1{font-size:14pt;text-align:center}h2{font-size:12pt;margin-top:20px}p{margin:6px 0}.firma{margin-top:50px;display:flex;justify-content:space-between;gap:40px}</style></head><body><h1>CONTRATTO DI COLLABORAZIONE COORDINATA E CONTINUATIVA</h1><h1>D.LGS. 28 FEBBRAIO 2021, N. 36</h1><p style="text-align:center;margin-top:4px"><strong>Settore Dilettantistico – Figura Tecnica: ALLENATORE</strong></p><h2>Tra le parti:</h2><p><strong>{{club_nome}}</strong> (di seguito "Società"), C.F. {{club_cf}}, con sede in {{club_indirizzo}}, rappresentata dal Presidente <strong>{{legale_nome}}</strong>,</p><p>e il Sig./Sig.ra <strong>{{collaboratore_nome}}</strong> (di seguito "Collaboratore"), nato/a a {{collaboratore_nato_a}} il {{collaboratore_data_nascita}}, C.F. {{collaboratore_cf}}, residente in {{collaboratore_indirizzo}};</p><h2>si conviene quanto segue:</h2><p><strong>Art. 1 – Oggetto.</strong> La Società affida al Collaboratore l''incarico di Allenatore della squadra {{nome_squadra}} (categoria {{categoria}}) per la stagione sportiva {{stagione}}.</p><p><strong>Art. 2 – Durata.</strong> Il presente contratto ha durata dal {{data_inizio}} al {{data_fine}}.</p><p><strong>Art. 3 – Compenso.</strong> La Società corrisponderà al Collaboratore un compenso lordo complessivo di € {{compenso_lordo}}, da erogarsi con le seguenti modalità: {{modalita_pagamento}}.</p><p><strong>Art. 4 – Trattamento fiscale.</strong> Il compenso è assoggettato al regime fiscale previsto dal D.Lgs. 36/2021 e successive modificazioni. La soglia di esenzione annua è pari a € 5.000,00.</p><p><strong>Art. 5 – Obblighi del Collaboratore.</strong> Il Collaboratore si impegna a svolgere l''attività con diligenza professionale, a rispettare il Regolamento interno della Società e le norme federali.</p><p><strong>Art. 6 – Riservatezza.</strong> Il Collaboratore si impegna a mantenere la riservatezza sulle informazioni relative alla Società e agli atleti.</p><p><strong>Art. 7 – Risoluzione.</strong> Il contratto può essere risolto con preavviso di {{preavviso}} giorni da entrambe le parti.</p><div class="firma"><div><p>Per la Società</p><br><p>________________________</p><p><strong>{{legale_nome}}</strong></p><p>Presidente</p></div><div><p>Il Collaboratore</p><br><p>________________________</p><p><strong>{{collaboratore_nome}}</strong></p></div></div><p style="margin-top:20px">Luogo e data: <strong>{{citta}}, {{data}}</strong></p></body></html>',
 '[{"chiave":"stagione","etichetta":"Stagione sportiva","tipo":"text"},{"chiave":"nome_squadra","etichetta":"Nome squadra","tipo":"text"},{"chiave":"categoria","etichetta":"Categoria","tipo":"text"},{"chiave":"collaboratore_nome","etichetta":"Nome collaboratore","tipo":"text"},{"chiave":"collaboratore_cf","etichetta":"CF collaboratore","tipo":"text"},{"chiave":"collaboratore_nato_a","etichetta":"Nato a","tipo":"text"},{"chiave":"collaboratore_data_nascita","etichetta":"Data nascita","tipo":"text"},{"chiave":"collaboratore_indirizzo","etichetta":"Indirizzo collaboratore","tipo":"text"},{"chiave":"compenso_lordo","etichetta":"Compenso lordo €","tipo":"text"},{"chiave":"modalita_pagamento","etichetta":"Modalità pagamento","tipo":"text"},{"chiave":"data_inizio","etichetta":"Data inizio","tipo":"text"},{"chiave":"data_fine","etichetta":"Data fine","tipo":"text"},{"chiave":"preavviso","etichetta":"Preavviso (giorni)","tipo":"text"},{"chiave":"data","etichetta":"Data firma","tipo":"text"}]'::jsonb,
 true, 10),

(NULL, 'contratti', 'Contratto Co.Co.Co. – Preparatore Atletico',
 'Contratto collaborazione per preparatore atletico D.Lgs. 36/2021',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:11pt;margin:40px;line-height:1.7}h1{font-size:13pt;text-align:center}h2{font-size:11pt;margin-top:16px}.firma{margin-top:40px;display:flex;justify-content:space-between}</style></head><body><h1>CONTRATTO DI COLLABORAZIONE – PREPARATORE ATLETICO</h1><h1>D.Lgs. 36/2021 – Settore Dilettantistico</h1><p>Tra <strong>{{club_nome}}</strong> (C.F. {{club_cf}}) e il Sig./Sig.ra <strong>{{collaboratore_nome}}</strong> (C.F. {{collaboratore_cf}})</p><h2>Art. 1 – Incarico</h2><p>Preparazione atletica squadra {{nome_squadra}}, stagione {{stagione}}, dal {{data_inizio}} al {{data_fine}}.</p><h2>Art. 2 – Compenso</h2><p>Compenso lordo complessivo: € {{compenso_lordo}}. Modalità: {{modalita_pagamento}}.</p><h2>Art. 3 – Regime fiscale</h2><p>D.Lgs. 36/2021, soglia esenzione € 5.000/anno, ritenuta d''acconto 23% sulla parte eccedente.</p><h2>Art. 4 – Riservatezza e obblighi</h2><p>Il collaboratore mantiene la riservatezza e rispetta i regolamenti federali.</p><div class="firma"><div><p>Per la Società<br><br>________________________<br><strong>{{legale_nome}}</strong></p></div><div><p>Il Collaboratore<br><br>________________________<br><strong>{{collaboratore_nome}}</strong></p></div></div><p><strong>{{citta}}, {{data}}</strong></p></body></html>',
 '[{"chiave":"stagione","etichetta":"Stagione","tipo":"text"},{"chiave":"nome_squadra","etichetta":"Squadra","tipo":"text"},{"chiave":"collaboratore_nome","etichetta":"Nome collaboratore","tipo":"text"},{"chiave":"collaboratore_cf","etichetta":"CF collaboratore","tipo":"text"},{"chiave":"compenso_lordo","etichetta":"Compenso lordo €","tipo":"text"},{"chiave":"modalita_pagamento","etichetta":"Modalità pagamento","tipo":"text"},{"chiave":"data_inizio","etichetta":"Data inizio","tipo":"text"},{"chiave":"data_fine","etichetta":"Data fine","tipo":"text"},{"chiave":"data","etichetta":"Data firma","tipo":"text"}]'::jsonb,
 true, 11),

(NULL, 'contratti', 'Contratto Prestazione Occasionale',
 'Contratto per prestazione occasionale (massimale €5.000/anno)',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:11pt;margin:40px;line-height:1.7}h1{font-size:13pt;text-align:center}.firma{margin-top:40px;display:flex;justify-content:space-between}</style></head><body><h1>CONTRATTO DI PRESTAZIONE OCCASIONALE</h1><p>Tra <strong>{{club_nome}}</strong> (C.F. {{club_cf}}, di seguito "Committente") e il Sig./Sig.ra <strong>{{prestatore_nome}}</strong> (C.F. {{prestatore_cf}}, di seguito "Prestatore").</p><p><strong>Oggetto:</strong> {{descrizione_attivita}}</p><p><strong>Data/e prestazione:</strong> {{date_prestazione}}</p><p><strong>Compenso:</strong> € {{compenso}} (lordo). Ai sensi dell''art. 2222 c.c. e D.Lgs. 36/2021 ove applicabile.</p><p><strong>Ritenuta d''acconto:</strong> {{ritenuta_acconto}}% ai sensi dell''art. 25 D.P.R. 600/1973.</p><p>Il Prestatore dichiara di non avere altri rapporti di lavoro dipendente o parasubordinato che possano configurare abitualità.</p><div class="firma"><div><p>Il Committente<br><br>________________________<br><strong>{{legale_nome}}</strong></p></div><div><p>Il Prestatore<br><br>________________________<br><strong>{{prestatore_nome}}</strong></p></div></div><p><strong>{{citta}}, {{data}}</strong></p></body></html>',
 '[{"chiave":"prestatore_nome","etichetta":"Nome prestatore","tipo":"text"},{"chiave":"prestatore_cf","etichetta":"CF prestatore","tipo":"text"},{"chiave":"descrizione_attivita","etichetta":"Descrizione attività","tipo":"textarea"},{"chiave":"date_prestazione","etichetta":"Date prestazione","tipo":"text"},{"chiave":"compenso","etichetta":"Compenso €","tipo":"text"},{"chiave":"ritenuta_acconto","etichetta":"Aliquota ritenuta %","tipo":"text"},{"chiave":"data","etichetta":"Data","tipo":"text"}]'::jsonb,
 true, 12),

(NULL, 'contratti', 'Accordo Economico – Calciatore Dilettante',
 'Accordo economico per calciatore dilettante ai sensi regolamento FIGC',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:11pt;margin:40px;line-height:1.7}h1{font-size:13pt;text-align:center}.firma{margin-top:40px;display:flex;justify-content:space-between}</style></head><body><h1>ACCORDO ECONOMICO – CALCIATORE DILETTANTE</h1><p>Tra la società <strong>{{club_nome}}</strong> e il calciatore <strong>{{atleta_nome}}</strong> (nato/a {{atleta_data_nascita}}, C.F. {{atleta_cf}}), per la stagione sportiva {{stagione}}.</p><p><strong>Rimborso spese mensile:</strong> € {{rimborso_mensile}}</p><p><strong>Premio presenza:</strong> € {{premio_presenza}} a partita</p><p><strong>Modalità erogazione:</strong> {{modalita}}</p><p>Il presente accordo non configura rapporto di lavoro. Le parti confermano la natura dilettantistica dell''attività.</p><div class="firma"><div><p>Per la Società<br><br>________________________<br><strong>{{legale_nome}}</strong></p></div><div><p>Il Calciatore<br><br>________________________<br><strong>{{atleta_nome}}</strong></p></div></div><p><strong>{{citta}}, {{data}}</strong></p></body></html>',
 '[{"chiave":"stagione","etichetta":"Stagione","tipo":"text"},{"chiave":"atleta_nome","etichetta":"Nome atleta","tipo":"text"},{"chiave":"atleta_cf","etichetta":"CF atleta","tipo":"text"},{"chiave":"atleta_data_nascita","etichetta":"Data nascita atleta","tipo":"text"},{"chiave":"rimborso_mensile","etichetta":"Rimborso mensile €","tipo":"text"},{"chiave":"premio_presenza","etichetta":"Premio presenza €","tipo":"text"},{"chiave":"modalita","etichetta":"Modalità erogazione","tipo":"text"},{"chiave":"data","etichetta":"Data","tipo":"text"}]'::jsonb,
 true, 13),

(NULL, 'contratti', 'Lettera di Incarico – Direttore Sportivo',
 'Lettera di nomina e incarico per il Direttore Sportivo',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:11pt;margin:40px;line-height:1.7}h1{font-size:13pt;text-align:center}.firma{margin-top:40px}</style></head><body><h1>LETTERA DI INCARICO – DIRETTORE SPORTIVO</h1><p>Egregio/a Sig./Sig.ra <strong>{{ds_nome}}</strong>,</p><p>Con la presente, il Consiglio Direttivo dell''ASD <strong>{{club_nome}}</strong>, riunito in data <strong>{{data_delibera}}</strong>, Le conferisce l''incarico di <strong>Direttore Sportivo</strong> per la stagione {{stagione}}.</p><p>Le competenze dell''incarico comprendono: gestione dei rapporti con i tesserati, coordinamento tecnico, rapporti con la federazione, trattative trasferimenti.</p><p><strong>Compenso:</strong> € {{compenso}} (regime D.Lgs. 36/2021).</p><p>La ringraziamo per la disponibilità e fiducia accordata.</p><div class="firma"><p>{{citta}}, {{data}}</p><br><p>Il Presidente<br><br>________________________<br><strong>{{legale_nome}}</strong></p></div></body></html>',
 '[{"chiave":"ds_nome","etichetta":"Nome DS","tipo":"text"},{"chiave":"stagione","etichetta":"Stagione","tipo":"text"},{"chiave":"data_delibera","etichetta":"Data delibera CdA","tipo":"text"},{"chiave":"compenso","etichetta":"Compenso €","tipo":"text"},{"chiave":"data","etichetta":"Data lettera","tipo":"text"}]'::jsonb,
 true, 14),

-- PRIVACY (5)
(NULL, 'privacy', 'Consenso Uso Immagine – Minore',
 'Autorizzazione all''uso delle immagini del minore per comunicazioni del club',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:11pt;margin:40px;line-height:1.7}h1{font-size:13pt;text-align:center}.firma{margin-top:40px;display:flex;justify-content:space-between}</style></head><body><h1>AUTORIZZAZIONE ALL''USO DELL''IMMAGINE DEL MINORE</h1><h1>Ai sensi dell''art. 96 Legge 22.04.1941, n. 633 e GDPR 2016/679</h1><p>Il/La sottoscritto/a <strong>{{genitore_nome}}</strong> (C.F. {{genitore_cf}}), in qualità di genitore/tutore del minore <strong>{{atleta_nome}}</strong>, nato/a il <strong>{{atleta_data_nascita}}</strong>,</p><p><strong>AUTORIZZA</strong></p><p>la società <strong>{{club_nome}}</strong> a fotografare e riprendere il proprio figlio/a durante le attività sportive e a utilizzare tali immagini per:</p><ul><li>Comunicazioni sui canali social ufficiali del club (Instagram, Facebook, ecc.)</li><li>Materiale promozionale non a fini commerciali</li><li>Archivio storico del club</li></ul><p>Le immagini non saranno cedute a terzi né utilizzate a fini commerciali. Il presente consenso può essere revocato in qualsiasi momento.</p><div class="firma"><div><p>Il genitore/tutore<br><br>________________________<br><strong>{{genitore_nome}}</strong></p></div><div><p>{{citta}}, {{data}}</p></div></div></body></html>',
 '[{"chiave":"genitore_nome","etichetta":"Nome genitore/tutore","tipo":"text"},{"chiave":"genitore_cf","etichetta":"CF genitore","tipo":"text"},{"chiave":"atleta_nome","etichetta":"Nome atleta","tipo":"text"},{"chiave":"atleta_data_nascita","etichetta":"Data nascita atleta","tipo":"text"},{"chiave":"data","etichetta":"Data","tipo":"text"}]'::jsonb,
 true, 20),

(NULL, 'privacy', 'Informativa GDPR – Trattamento Dati Personali',
 'Informativa completa sul trattamento dei dati personali (soci e atleti)',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:10pt;margin:40px;line-height:1.6}h1{font-size:13pt;text-align:center}h2{font-size:11pt;margin-top:14px}p{margin:4px 0}.firma{margin-top:30px;display:flex;justify-content:space-between}</style></head><body><h1>INFORMATIVA SUL TRATTAMENTO DEI DATI PERSONALI</h1><h1>Ai sensi degli artt. 13 e 14 del Reg. UE 2016/679 (GDPR)</h1><h2>1. Titolare del trattamento</h2><p><strong>{{club_nome}}</strong>, C.F. {{club_cf}}, con sede in {{club_indirizzo}}. Contatto: {{club_email}}.</p><h2>2. Dati trattati</h2><p>Dati anagrafici, di contatto, sanitari (certificati medici), immagini, dati di pagamento.</p><h2>3. Finalità e base giuridica</h2><p>a) Gestione del rapporto associativo e sportivo (esecuzione contratto); b) Adempimenti fiscali e previdenziali (obbligo legale); c) Comunicazioni istituzionali (legittimo interesse); d) Marketing/comunicazione promozionale (consenso).</p><h2>4. Conservazione</h2><p>I dati sono conservati per la durata del rapporto associativo e per il periodo previsto dalla normativa fiscale (10 anni).</p><h2>5. Diritti dell''interessato</h2><p>Accesso, rettifica, cancellazione, limitazione, portabilità, opposizione. Reclamo all''Autorità Garante (www.garanteprivacy.it).</p><h2>6. Comunicazione a terzi</h2><p>Federazioni sportive, commercialisti, istituti bancari, enti previdenziali. Non viene effettuata vendita di dati.</p><div class="firma"><div><p>Firma per presa visione<br><br>________________________</p></div><div><p>{{citta}}, {{data}}</p></div></div></body></html>',
 '[{"chiave":"data","etichetta":"Data","tipo":"text"}]'::jsonb,
 true, 21),

(NULL, 'privacy', 'Consenso Comunicazioni Commerciali',
 'Modulo di consenso per ricezione newsletter e comunicazioni promozionali',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:11pt;margin:40px;line-height:1.7}.firma{margin-top:40px}</style></head><body><h1 style="text-align:center">CONSENSO COMUNICAZIONI PROMOZIONALI</h1><p>Il/La sottoscritto/a <strong>{{nome_cognome}}</strong> (C.F. {{cf}}), socio/a dell''ASD <strong>{{club_nome}}</strong>,</p><p>□ <strong>ACCONSENTE</strong> &nbsp;&nbsp; □ <strong>NON ACCONSENTE</strong></p><p>a ricevere comunicazioni promozionali, newsletter e aggiornamenti relativi alle attività del club tramite email, SMS e canali social.</p><p>Il consenso può essere revocato in qualsiasi momento scrivendo a {{club_email}}.</p><div class="firma"><p>{{citta}}, {{data}}</p><br><p>________________________<br><strong>{{nome_cognome}}</strong></p></div></body></html>',
 '[{"chiave":"nome_cognome","etichetta":"Nome e Cognome","tipo":"text"},{"chiave":"cf","etichetta":"Codice Fiscale","tipo":"text"},{"chiave":"data","etichetta":"Data","tipo":"text"}]'::jsonb,
 true, 22),

(NULL, 'privacy', 'Nomina DPO / Responsabile Privacy',
 'Nomina del Responsabile della Protezione dei Dati (DPO)',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:11pt;margin:40px;line-height:1.7}.firma{margin-top:40px;display:flex;justify-content:space-between}</style></head><body><h1 style="text-align:center">NOMINA A RESPONSABILE DELLA PROTEZIONE DEI DATI (DPO)</h1><p>Con la presente, il Titolare del trattamento <strong>{{club_nome}}</strong> (C.F. {{club_cf}}), in persona del Presidente <strong>{{legale_nome}}</strong>, nomina il Sig./Sig.ra <strong>{{dpo_nome}}</strong> (C.F. {{dpo_cf}}) quale Responsabile della Protezione dei Dati ai sensi dell''art. 37 del GDPR 2016/679.</p><p>Il DPO nominato si impegna ad assolvere i compiti previsti dall''art. 39 del GDPR e dalle Linee Guida del Garante.</p><div class="firma"><div><p>Il Titolare<br><br>________________________<br><strong>{{legale_nome}}</strong></p></div><div><p>Il DPO nominato<br><br>________________________<br><strong>{{dpo_nome}}</strong></p></div></div><p><strong>{{citta}}, {{data}}</strong></p></body></html>',
 '[{"chiave":"dpo_nome","etichetta":"Nome DPO","tipo":"text"},{"chiave":"dpo_cf","etichetta":"CF DPO","tipo":"text"},{"chiave":"data","etichetta":"Data","tipo":"text"}]'::jsonb,
 true, 23),

(NULL, 'privacy', 'Liberatoria Generale – Immagini e Video',
 'Liberatoria per pubblicazione immagini e video su tutti i canali',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:11pt;margin:40px;line-height:1.7}.firma{margin-top:40px;display:flex;justify-content:space-between}</style></head><body><h1 style="text-align:center">LIBERATORIA USO IMMAGINI E VIDEO</h1><p>Il/La sottoscritto/a <strong>{{nome_cognome}}</strong> □ personalmente &nbsp; □ in qualità di genitore/tutore di <strong>{{minore_nome}}</strong>,</p><p><strong>AUTORIZZA</strong> incondizionatamente la società <strong>{{club_nome}}</strong> alla pubblicazione delle proprie immagini/video acquisiti durante le attività sportive su: sito web, social network (Instagram, Facebook, YouTube, TikTok), comunicati stampa, materiale promozionale.</p><p>La presente liberatoria ha validità per tutta la durata del rapporto associativo con {{club_nome}}.</p><div class="firma"><div><p>Firma<br><br>________________________<br><strong>{{nome_cognome}}</strong></p></div><div><p>{{citta}}, {{data}}</p></div></div></body></html>',
 '[{"chiave":"nome_cognome","etichetta":"Nome e Cognome firmatario","tipo":"text"},{"chiave":"minore_nome","etichetta":"Nome minore (se applicabile)","tipo":"text"},{"chiave":"data","etichetta":"Data","tipo":"text"}]'::jsonb,
 true, 24),

-- TESSERAMENTO (5)
(NULL, 'tesseramento', 'Modulo di Iscrizione / Domanda di Tesseramento',
 'Modulo standard per richiesta di tesseramento atleta',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:11pt;margin:40px;line-height:1.7}h1{font-size:13pt;text-align:center}table{width:100%;margin:10px 0}td{padding:4px 8px;border-bottom:1px solid #ddd;font-size:11pt}.firma{margin-top:30px;display:flex;justify-content:space-between}</style></head><body><h1>{{club_nome}}</h1><h1>DOMANDA DI TESSERAMENTO – Stagione {{stagione}}</h1><table><tr><td><strong>Cognome e Nome:</strong></td><td>{{atleta_nome}}</td></tr><tr><td><strong>Nato/a il:</strong></td><td>{{atleta_data_nascita}}</td></tr><tr><td><strong>a:</strong></td><td>{{atleta_nato_a}}</td></tr><tr><td><strong>Codice Fiscale:</strong></td><td>{{atleta_cf}}</td></tr><tr><td><strong>Residenza:</strong></td><td>{{atleta_indirizzo}}</td></tr><tr><td><strong>Telefono:</strong></td><td>{{atleta_telefono}}</td></tr><tr><td><strong>Email:</strong></td><td>{{atleta_email}}</td></tr><tr><td><strong>Squadra richiesta:</strong></td><td>{{nome_squadra}}</td></tr><tr><td><strong>Genitore/Tutore:</strong></td><td>{{genitore_nome}}</td></tr></table><p>Il/La sottoscritto/a dichiara di aver preso visione dello Statuto e del Regolamento Interno e di accettarli integralmente.</p><div class="firma"><div><p>Firma richiedente/genitore<br><br>________________________</p></div><div><p>{{citta}}, {{data}}</p></div></div></body></html>',
 '[{"chiave":"stagione","etichetta":"Stagione","tipo":"text"},{"chiave":"atleta_nome","etichetta":"Nome atleta","tipo":"text"},{"chiave":"atleta_data_nascita","etichetta":"Data nascita","tipo":"text"},{"chiave":"atleta_nato_a","etichetta":"Nato a","tipo":"text"},{"chiave":"atleta_cf","etichetta":"CF atleta","tipo":"text"},{"chiave":"atleta_indirizzo","etichetta":"Indirizzo atleta","tipo":"text"},{"chiave":"atleta_telefono","etichetta":"Telefono","tipo":"text"},{"chiave":"atleta_email","etichetta":"Email","tipo":"text"},{"chiave":"nome_squadra","etichetta":"Squadra","tipo":"text"},{"chiave":"genitore_nome","etichetta":"Nome genitore","tipo":"text"},{"chiave":"data","etichetta":"Data","tipo":"text"}]'::jsonb,
 true, 30),

(NULL, 'tesseramento', 'Conferma Tesseramento – Ricevuta',
 'Ricevuta di conferma avvenuto tesseramento con numero tessera',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:11pt;margin:40px;line-height:1.7}h1{font-size:13pt;text-align:center}.box{border:2px solid #000;padding:16px;margin:20px 0;text-align:center}.firma{margin-top:30px}</style></head><body><h1>{{club_nome}}</h1><h1>CONFERMA DI TESSERAMENTO</h1><div class="box"><p style="font-size:14pt;font-weight:bold">NUMERO TESSERA: {{numero_tessera}}</p><p>Stagione sportiva: <strong>{{stagione}}</strong></p></div><p>Si certifica che l''atleta <strong>{{atleta_nome}}</strong>, nato/a il <strong>{{atleta_data_nascita}}</strong> (C.F. {{atleta_cf}}), è regolarmente tesserato/a con la società <strong>{{club_nome}}</strong> per la stagione sportiva {{stagione}}.</p><p>Squadra: <strong>{{nome_squadra}}</strong> | Categoria: <strong>{{categoria}}</strong></p><div class="firma"><p>{{citta}}, {{data}}</p><br><p>Il Segretario<br><br>________________________</p></div></body></html>',
 '[{"chiave":"numero_tessera","etichetta":"Numero tessera","tipo":"text"},{"chiave":"stagione","etichetta":"Stagione","tipo":"text"},{"chiave":"atleta_nome","etichetta":"Nome atleta","tipo":"text"},{"chiave":"atleta_data_nascita","etichetta":"Data nascita","tipo":"text"},{"chiave":"atleta_cf","etichetta":"CF atleta","tipo":"text"},{"chiave":"nome_squadra","etichetta":"Squadra","tipo":"text"},{"chiave":"categoria","etichetta":"Categoria","tipo":"text"},{"chiave":"data","etichetta":"Data","tipo":"text"}]'::jsonb,
 true, 31),

(NULL, 'tesseramento', 'Modulo Rinnovo Tesseramento',
 'Domanda di rinnovo tesseramento per stagione successiva',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:11pt;margin:40px;line-height:1.7}h1{font-size:13pt;text-align:center}.firma{margin-top:30px;display:flex;justify-content:space-between}</style></head><body><h1>{{club_nome}}</h1><h1>RINNOVO TESSERAMENTO – Stagione {{stagione}}</h1><p>Il/La sottoscritto/a <strong>{{genitore_nome}}</strong> (genitore/tutore) / <strong>{{atleta_nome}}</strong> (se maggiorenne), chiede il rinnovo del tesseramento dell''atleta <strong>{{atleta_nome}}</strong> (C.F. {{atleta_cf}}) per la stagione {{stagione}}.</p><p>Tessera precedente n.: <strong>{{tessera_precedente}}</strong> | Squadra: <strong>{{nome_squadra}}</strong></p><p>Dichiara che i dati anagrafici non sono variati □ &nbsp; oppure che le variazioni sono le seguenti: _______________</p><div class="firma"><div><p>Firma<br><br>________________________</p></div><div><p>{{citta}}, {{data}}</p></div></div></body></html>',
 '[{"chiave":"stagione","etichetta":"Stagione nuova","tipo":"text"},{"chiave":"atleta_nome","etichetta":"Nome atleta","tipo":"text"},{"chiave":"atleta_cf","etichetta":"CF atleta","tipo":"text"},{"chiave":"genitore_nome","etichetta":"Nome genitore","tipo":"text"},{"chiave":"tessera_precedente","etichetta":"N. tessera precedente","tipo":"text"},{"chiave":"nome_squadra","etichetta":"Squadra","tipo":"text"},{"chiave":"data","etichetta":"Data","tipo":"text"}]'::jsonb,
 true, 32),

(NULL, 'tesseramento', 'Svincolo Atleta',
 'Richiesta di svincolo / trasferimento atleta ad altra società',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:11pt;margin:40px;line-height:1.7}h1{font-size:13pt;text-align:center}.firma{margin-top:40px;display:flex;justify-content:space-between}</style></head><body><h1>RICHIESTA DI SVINCOLO ATLETA</h1><p>Il/La sottoscritto/a <strong>{{richiedente_nome}}</strong> (genitore/tutore dell''atleta / atleta maggiorenne), chiede lo svincolo dell''atleta <strong>{{atleta_nome}}</strong> (C.F. {{atleta_cf}}), attualmente tesserato/a con <strong>{{club_nome}}</strong> (tessera n. {{numero_tessera}}), a decorrere dal <strong>{{data_svincolo}}</strong>.</p><p>Motivazione: {{motivazione}}</p><p>La società di destinazione è: <strong>{{societa_destinazione}}</strong>.</p><p>Il richiedente dichiara che non esistono pendenze economiche o disciplinari.</p><div class="firma"><div><p>Firma richiedente<br><br>________________________</p></div><div><p>Visto Società – Il Presidente<br><br>________________________<br><strong>{{legale_nome}}</strong></p></div></div><p><strong>{{citta}}, {{data}}</strong></p></body></html>',
 '[{"chiave":"richiedente_nome","etichetta":"Nome richiedente","tipo":"text"},{"chiave":"atleta_nome","etichetta":"Nome atleta","tipo":"text"},{"chiave":"atleta_cf","etichetta":"CF atleta","tipo":"text"},{"chiave":"numero_tessera","etichetta":"N. tessera","tipo":"text"},{"chiave":"data_svincolo","etichetta":"Data svincolo","tipo":"text"},{"chiave":"motivazione","etichetta":"Motivazione","tipo":"textarea"},{"chiave":"societa_destinazione","etichetta":"Società destinazione","tipo":"text"},{"chiave":"data","etichetta":"Data","tipo":"text"}]'::jsonb,
 true, 33),

(NULL, 'tesseramento', 'Certificato Partecipazione Attività Sportiva',
 'Attestato di partecipazione per l''atleta (uso scolastico/personale)',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:11pt;margin:40px;line-height:1.7;text-align:center}h1{font-size:16pt;border-bottom:3px solid #000;padding-bottom:8px}h2{font-size:13pt}.box{border:2px solid #000;padding:20px;margin:30px auto;max-width:500px}.firma{margin-top:40px;display:flex;justify-content:space-between;text-align:left}</style></head><body><h1>{{club_nome}}</h1><h2>ATTESTATO DI PARTECIPAZIONE</h2><div class="box"><p>Si certifica che</p><p style="font-size:16pt;font-weight:bold">{{atleta_nome}}</p><p>nato/a il <strong>{{atleta_data_nascita}}</strong></p><p>ha partecipato alle attività sportive dilettantistiche della categoria <strong>{{categoria}}</strong> per la stagione sportiva <strong>{{stagione}}</strong>.</p></div><div class="firma"><div><p>{{citta}}, {{data}}</p></div><div><p>Il Presidente<br><br>________________________<br><strong>{{legale_nome}}</strong></p></div></div></body></html>',
 '[{"chiave":"stagione","etichetta":"Stagione","tipo":"text"},{"chiave":"atleta_nome","etichetta":"Nome atleta","tipo":"text"},{"chiave":"atleta_data_nascita","etichetta":"Data nascita","tipo":"text"},{"chiave":"categoria","etichetta":"Categoria","tipo":"text"},{"chiave":"data","etichetta":"Data","tipo":"text"}]'::jsonb,
 true, 34),

-- VARIE (3)
(NULL, 'varie', 'Procura Speciale',
 'Delega/procura a terzi per operazioni specifiche',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:11pt;margin:40px;line-height:1.7}h1{font-size:13pt;text-align:center}.firma{margin-top:40px;display:flex;justify-content:space-between}</style></head><body><h1>PROCURA SPECIALE</h1><p>Il/La sottoscritto/a <strong>{{delegante_nome}}</strong> (C.F. {{delegante_cf}}), in qualità di {{delegante_ruolo}} dell''ASD <strong>{{club_nome}}</strong>,</p><p><strong>CONFERISCE PROCURA SPECIALE</strong></p><p>al Sig./Sig.ra <strong>{{delegato_nome}}</strong> (C.F. {{delegato_cf}}), affinché in nome e per conto della scrivente società, possa: {{oggetto_procura}}.</p><p>La presente procura è valida fino al {{scadenza}} e non è delegabile a terzi.</p><div class="firma"><div><p>Il Delegante<br><br>________________________<br><strong>{{delegante_nome}}</strong></p></div><div><p>Il Delegato (per accettazione)<br><br>________________________<br><strong>{{delegato_nome}}</strong></p></div></div><p><strong>{{citta}}, {{data}}</strong></p></body></html>',
 '[{"chiave":"delegante_nome","etichetta":"Nome delegante","tipo":"text"},{"chiave":"delegante_cf","etichetta":"CF delegante","tipo":"text"},{"chiave":"delegante_ruolo","etichetta":"Ruolo delegante","tipo":"text"},{"chiave":"delegato_nome","etichetta":"Nome delegato","tipo":"text"},{"chiave":"delegato_cf","etichetta":"CF delegato","tipo":"text"},{"chiave":"oggetto_procura","etichetta":"Oggetto procura","tipo":"textarea"},{"chiave":"scadenza","etichetta":"Scadenza","tipo":"text"},{"chiave":"data","etichetta":"Data","tipo":"text"}]'::jsonb,
 true, 40),

(NULL, 'varie', 'Comunicato Ufficiale al Comitato',
 'Template comunicato ufficiale per comunicazioni alla federazione/comitato',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:11pt;margin:40px;line-height:1.7}h1{font-size:13pt}.firma{margin-top:40px}</style></head><body><h1>{{club_nome}} – COMUNICATO UFFICIALE N. {{numero_comunicato}}</h1><p>Alla cortese attenzione di: <strong>{{destinatario}}</strong></p><p>La scrivente ASD <strong>{{club_nome}}</strong>, affiliata {{federazione}} con il codice {{figc_codice}}, con la presente comunica quanto segue:</p><p>{{testo_comunicato}}</p><p>Si rimane a disposizione per eventuali chiarimenti.</p><div class="firma"><p>{{citta}}, {{data}}</p><br><p>Il Presidente: ________________________<br><strong>{{legale_nome}}</strong><br><br>Il Segretario: ________________________</p></div></body></html>',
 '[{"chiave":"numero_comunicato","etichetta":"N. comunicato","tipo":"text"},{"chiave":"destinatario","etichetta":"Destinatario","tipo":"text"},{"chiave":"federazione","etichetta":"Federazione","tipo":"text"},{"chiave":"testo_comunicato","etichetta":"Testo comunicato","tipo":"textarea"},{"chiave":"data","etichetta":"Data","tipo":"text"}]'::jsonb,
 true, 41),

(NULL, 'varie', 'Ricevuta Pagamento Quota Associativa',
 'Ricevuta per pagamento quota sociale/iscrizione',
 '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>body{font-family:Arial,sans-serif;font-size:11pt;margin:40px;line-height:1.7}h1{font-size:13pt;text-align:center}.box{border:2px dashed #666;padding:16px;margin:16px 0}.firma{margin-top:30px;display:flex;justify-content:space-between}</style></head><body><h1>{{club_nome}} – RICEVUTA DI PAGAMENTO</h1><div class="box"><p><strong>Ricevuta n.:</strong> {{numero_ricevuta}}</p><p><strong>Data:</strong> {{data}}</p><p><strong>Pagante:</strong> {{nome_pagante}} (C.F. {{cf_pagante}})</p><p><strong>Causale:</strong> {{causale}}</p><p><strong>Importo:</strong> € {{importo}}</p><p><strong>Modalità:</strong> {{modalita}}</p></div><p>Si rilascia la presente ricevuta a titolo di quietanza.</p><div class="firma"><div><p>Il Tesoriere / Segretario<br><br>________________________</p></div><div><p>Il Pagante<br><br>________________________</p></div></div></body></html>',
 '[{"chiave":"numero_ricevuta","etichetta":"N. ricevuta","tipo":"text"},{"chiave":"nome_pagante","etichetta":"Nome pagante","tipo":"text"},{"chiave":"cf_pagante","etichetta":"CF pagante","tipo":"text"},{"chiave":"causale","etichetta":"Causale pagamento","tipo":"text"},{"chiave":"importo","etichetta":"Importo €","tipo":"text"},{"chiave":"modalita","etichetta":"Modalità pagamento","tipo":"text"},{"chiave":"data","etichetta":"Data","tipo":"text"}]'::jsonb,
 true, 42);
