export interface OnboardingStep {
  id: string
  title: string
  problem: string
  solution: string
  route: string
  targetSelector: string
  guideText: string
}

const ONBOARDING_SEGRETARIO: OnboardingStep[] = [
  {
    id: 'anagrafica',
    title: 'Gestione Anagrafica',
    problem: 'Hai i dati dei giocatori su fogli Excel, WhatsApp e foglietti di carta separati?',
    solution: 'Con ClubIS hai tutti i giocatori in un unico archivio digitale, sempre aggiornato.',
    route: '/dashboard/segretario/giocatori',
    targetSelector: "[data-onboarding='btn-aggiungi-giocatore']",
    guideText: "Clicca '+ Aggiungi giocatore' per inserire il primo giocatore. Puoi anche importare una lista intera da Excel con un solo file CSV.",
  },
  {
    id: 'tesseramenti',
    title: 'Tesseramenti',
    problem: 'Sai sempre quanti giocatori sono in prestito e quanti tesserati definitivamente?',
    solution: 'ClubIS tiene traccia di ogni tipo di tesseramento con lo stato aggiornato in tempo reale.',
    route: '/dashboard/segretario/tesseramenti',
    targetSelector: "[data-onboarding='btn-nuovo-tesseramento']",
    guideText: "Clicca '+ Nuovo tesseramento' e seleziona il tipo: definitivo, prestito, prova, svincolo. Il codice tessera FIGC viene registrato automaticamente.",
  },
  {
    id: 'certificati',
    title: 'Certificati Medici',
    problem: 'Ti è già capitato di scoprire un certificato scaduto la sera prima di una partita?',
    solution: 'ClubIS ti avvisa in automatico quando un certificato sta per scadere, con 30 giorni e 7 giorni di anticipo.',
    route: '/dashboard/segretario/certificati',
    targetSelector: "[data-onboarding='section-certificati-scadenza']",
    guideText: "Questa sezione mostra tutti i certificati in scadenza nei prossimi 30 giorni. Clicca 'Rinnova' direttamente dalla lista senza reinserire i dati.",
  },
  {
    id: 'partite',
    title: 'Calendario Partite',
    problem: 'Inserisci ancora le partite una per una a mano ogni stagione?',
    solution: 'ClubIS importa il calendario dal PDF ufficiale FIGC in pochi secondi.',
    route: '/dashboard/segretario/partite',
    targetSelector: "[data-onboarding='btn-importa-calendario']",
    guideText: "Clicca 'Importa da PDF' per caricare il calendario ufficiale della FIGC. Tutte le partite vengono create automaticamente. Puoi anche aggiungerne una singola con '+ Nuova partita'.",
  },
  {
    id: 'distinte',
    title: 'Distinte Gara',
    problem: 'Quanto tempo perdi ogni settimana a compilare la distinta su carta prima di ogni partita?',
    solution: 'ClubIS genera la distinta ufficiale pronta per la stampa in 30 secondi.',
    route: '/dashboard/segretario/distinte',
    targetSelector: "[data-onboarding='btn-genera-distinta']",
    guideText: "Seleziona la partita, clicca 'Genera distinta' e scegli i convocati dalla lista. La distinta esce già formattata per il direttore di gara.",
  },
  {
    id: 'pagamenti',
    title: 'Quote e Pagamenti',
    problem: 'Rincorri ancora le famiglie con messaggi su WhatsApp per le quote non pagate?',
    solution: 'ClubIS mostra chi non ha pagato e invia i solleciti direttamente dal sistema.',
    route: '/dashboard/segretario/pagamenti',
    targetSelector: "[data-onboarding='section-arretrati']",
    guideText: "Qui vedi il totale degli arretrati e chi è in ritardo. Clicca 'Sollecita' accanto a un giocatore per inviare un avviso direttamente in-app o via email.",
  },
  {
    id: 'prima-nota',
    title: 'Prima Nota',
    problem: 'Tieni le entrate e le uscite del club su un foglio Excel o, peggio, su carta?',
    solution: 'ClubIS registra ogni movimento e calcola il saldo del club in tempo reale.',
    route: '/dashboard/segretario/prima-nota',
    targetSelector: "[data-onboarding='btn-nuova-entrata']",
    guideText: "Usa '+ Entrata' o '+ Uscita' per registrare ogni movimento. Seleziona la categoria, inserisci importo e descrizione. Il saldo si aggiorna istantaneamente.",
  },
  {
    id: 'figc',
    title: 'Conformità FIGC',
    problem: 'Passi 30 minuti a leggere ogni Comunicato Ufficiale FIGC per trovare le squalifiche dei tuoi giocatori?',
    solution: 'ClubIS legge il PDF del comunicato e applica le squalifiche ai giocatori con un click.',
    route: '/dashboard/segretario/figc/comunicati',
    targetSelector: "[data-onboarding='btn-carica-cu']",
    guideText: "Clicca 'Carica C.U.' e seleziona il PDF del Comunicato Ufficiale FIGC. Il sistema identifica automaticamente le squalifiche e le abbina ai giocatori della rosa. Approva con un click.",
  },
  {
    id: 'documenti',
    title: 'Libreria Documenti',
    problem: 'Crei ancora i contratti e le liberatorie da zero ogni volta con Word?',
    solution: 'ClubIS ha una libreria di modelli ufficiali che compila automaticamente con i dati del giocatore.',
    route: '/dashboard/segretario/documenti',
    targetSelector: "[data-onboarding='btn-genera-documento']",
    guideText: "Seleziona il tipo di documento dal catalogo (contratto, liberatoria, comunicazione...), scegli il giocatore e ClubIS compila tutti i campi in automatico. Stampa o salva in PDF.",
  },
  {
    id: 'sepa',
    title: 'Rimborsi SEPA',
    problem: 'Fai ancora i bonifici di rimborso uno per uno dalla tua banca online ogni mese?',
    solution: 'ClubIS genera il file XML SEPA per tutti i rimborsi del mese in un solo click.',
    route: '/dashboard/segretario/rimborsi',
    targetSelector: "[data-onboarding='btn-genera-sepa']",
    guideText: "Seleziona il mese di riferimento e clicca 'Genera file SEPA'. Il sistema crea automaticamente il file XML compatibile con la tua banca. Scaricalo e caricalo sul conto del club.",
  },
  {
    id: 'accrediti',
    title: 'Accrediti Stadio',
    problem: 'Gestisci ancora gli accrediti per le partite su un foglio di carta o via WhatsApp?',
    solution: 'ClubIS tiene traccia di tutti gli accrediti per partita: media, sponsor, ospiti VIP e collaboratori.',
    route: '/dashboard/segretario/accrediti',
    targetSelector: "[data-onboarding='section-accrediti']",
    guideText: 'Seleziona la partita e aggiungi gli accrediti per categoria. Ogni accreditato viene registrato con nome, categoria e badge. La lista è disponibile al tornello il giorno della gara.',
  },
  {
    id: 'scadenze-figc',
    title: 'Scadenze FIGC',
    problem: 'Hai mai perso una scadenza federale perché nessuno l\'aveva segnata da nessuna parte?',
    solution: 'ClubIS raccoglie tutte le scadenze FIGC in un calendario unico con alert automatici.',
    route: '/dashboard/segretario/scadenze-figc',
    targetSelector: "[data-onboarding='btn-nuova-scadenza']",
    guideText: "Clicca '+ Nuova scadenza' per aggiungere una scadenza federale. Puoi caricare le scadenze standard FIGC con un click. Il sistema ti avvisa automaticamente 7 e 3 giorni prima.",
  },
  {
    id: 'squalifiche',
    title: 'Monitor Squalifiche',
    problem: 'Scopri le squalifiche dei tuoi giocatori leggendo il PDF del C.U. FIGC manualmente ogni settimana?',
    solution: 'ClubIS monitora le squalifiche e le applica automaticamente alle distinte gara.',
    route: '/dashboard/segretario/squalifiche',
    targetSelector: "[data-onboarding='btn-inserisci-squalifica']",
    guideText: "Clicca '+ Inserisci squalifica' per registrare manualmente una squalifica, oppure usa l'importazione da C.U. FIGC nella sezione FIGC. Le squalifiche vengono bloccate automaticamente nelle distinte.",
  },
  {
    id: 'portafoglio-figc',
    title: 'Portafoglio FIGC',
    problem: 'Sai sempre quanti crediti hai nel portafoglio FIGC per i tesseramenti e le pratiche?',
    solution: 'ClubIS traccia il saldo del portafoglio FIGC e ogni ricarica effettuata.',
    route: '/dashboard/segretario/figc/portafoglio',
    targetSelector: "[data-onboarding='btn-registra-ricarica']",
    guideText: "Clicca '+ Registra ricarica' ogni volta che ricarichi il portafoglio FIGC. Il sistema calcola il saldo residuo e ti avvisa quando sta per esaurirsi.",
  },
  {
    id: 'fornitori',
    title: 'Fornitori e Clienti',
    problem: 'I dati di fornitori e clienti del club sono sparsi su email, fogli Excel e biglietti da visita?',
    solution: 'ClubIS centralizza anagrafiche di fornitori e clienti con storico movimenti per ognuno.',
    route: '/dashboard/segretario/fornitori',
    targetSelector: "[data-onboarding='btn-nuovo-fornitore']",
    guideText: "Clicca '+ Nuovo' per aggiungere un fornitore o cliente. Inserisci ragione sociale, P.IVA, IBAN e condizioni di pagamento. Puoi registrare i movimenti direttamente dalla scheda.",
  },
  {
    id: 'quietanze',
    title: 'Quietanze',
    problem: 'Emetti ancora le quietanze di pagamento una per una con Word o Excel?',
    solution: 'ClubIS genera tutte le quietanze del periodo in un solo click, già numerate e archiviate.',
    route: '/dashboard/segretario/quietanze',
    targetSelector: "[data-onboarding='btn-genera-quietanze']",
    guideText: "Clicca 'Genera tutte le quietanze' per creare automaticamente le quietanze per tutti i pagamenti del periodo selezionato. Ogni quietanza è numerata progressivamente e pronta per la firma.",
  },
  {
    id: 'registro-iva',
    title: 'Registro IVA',
    problem: 'Il commercialista del club ti chiede il registro IVA e devi ricostruirlo da zero ogni trimestre?',
    solution: 'ClubIS genera il registro IVA sincronizzando automaticamente tutti i movimenti rilevanti.',
    route: '/dashboard/segretario/registro-iva',
    targetSelector: "[data-onboarding='btn-sincronizza-iva']",
    guideText: "Clicca 'Sincronizza pagamenti' per aggiornare il registro con tutti i movimenti dell'anno. Il registro è esportabile in CSV per il commercialista con un click.",
  },
  {
    id: 'compensi',
    title: 'Compensi Collaboratori',
    problem: 'I compensi dei collaboratori sportivi sono tracciati su un foglio Excel condiviso su WhatsApp?',
    solution: 'ClubIS gestisce i compensi in conformità alla Riforma Sport (D.Lgs. 36/2021) con soglie automatiche.',
    route: '/dashboard/segretario/compensi',
    targetSelector: "[data-onboarding='btn-nuovo-compenso']",
    guideText: "Clicca '+ Nuovo compenso' per registrare un compenso a un collaboratore. Il sistema calcola automaticamente se supera la soglia esente da contributi e genera il prospetto per il 770.",
  },
]

const ONBOARDING_PRESIDENTE: OnboardingStep[] = [
  {
    id: 'dashboard-kpi',
    title: 'Panoramica Esecutiva',
    problem: 'Devi chiamare il segretario o il DS ogni volta che vuoi sapere come sta andando il club?',
    solution: 'La tua dashboard mostra in tempo reale tutti i KPI del club: giocatori, finanze, partite.',
    route: '/dashboard/presidente',
    targetSelector: "[data-onboarding='section-kpi-overview']",
    guideText: 'Questa è la tua vista di controllo. Qui vedi giocatori tesserati, entrate del mese, quote arretrate e ultimi risultati. Tutto aggiornato in tempo reale senza chiedere a nessuno.',
  },
  {
    id: 'finanze',
    title: 'Finanze e Budget',
    problem: 'Sai sempre con precisione se il club sta rispettando il budget annuale?',
    solution: 'ClubIS monitora entrate, uscite e Financial Fair Play con grafici chiari.',
    route: '/dashboard/presidente/finanze',
    targetSelector: "[data-onboarding='section-budget-annuale']",
    guideText: "Qui trovi il budget annuale diviso per categoria. Il grafico mostra l'andamento mensile e l'indicatore FFP segnala subito se sei fuori dai parametri.",
  },
  {
    id: 'sponsor',
    title: 'Sponsor',
    problem: 'Hai ancora i contratti degli sponsor in una cartella su email o in un cassetto?',
    solution: 'ClubIS gestisce tutti gli sponsor con importi, tipologie e contributo totale.',
    route: '/dashboard/presidente/sponsor',
    targetSelector: "[data-onboarding='btn-aggiungi-sponsor']",
    guideText: "Clicca '+ Aggiungi sponsor' per registrare nome, categoria (gold/silver/bronze) e importo del contratto. Il totale dei contributi si aggiorna automaticamente.",
  },
  {
    id: 'staff',
    title: 'Staff e Organigramma',
    problem: 'I collaboratori del club sanno già usare ClubIS? Invitali in pochi secondi.',
    solution: 'ClubIS genera un link di invito personalizzato per ogni membro dello staff.',
    route: '/dashboard/presidente/inviti',
    targetSelector: "[data-onboarding='btn-invita-staff']",
    guideText: "Clicca 'Invita membro' e inserisci email e ruolo. Il collaboratore riceve un link di accesso e vede solo la sua dashboard dedicata.",
  },
  {
    id: 'obiettivi',
    title: 'Obiettivi Stagionali',
    problem: 'Gli obiettivi della stagione esistono solo nella tua testa o in un documento che nessuno aggiorna?',
    solution: 'ClubIS tiene traccia degli obiettivi stagionali e monitora i progressi nel tempo.',
    route: '/dashboard/presidente/obiettivi',
    targetSelector: "[data-onboarding='btn-nuovo-obiettivo']",
    guideText: "Definisci gli obiettivi sportivi e organizzativi della stagione. ClubIS aggiorna i progressi automaticamente man mano che arrivano i risultati.",
  },
  {
    id: 'report',
    title: 'Report Mensile',
    problem: 'Preparare il report per il consiglio direttivo ti porta via mezza giornata ogni mese?',
    solution: 'ClubIS genera il report mensile completo con tutti i KPI in un click.',
    route: '/dashboard/presidente/report',
    targetSelector: "[data-onboarding='btn-genera-report']",
    guideText: "Seleziona il mese e clicca 'Genera report'. Ottieni un documento completo con dati sportivi, economici e organizzativi, pronto per essere esportato e presentato.",
  },
  {
    id: 'impianti',
    title: 'Impianti e Stadio',
    problem: 'Come vieni a sapere di un guasto urgente all\'impianto? Aspetti che qualcuno ti chiami?',
    solution: 'Il custode segnala i problemi su ClubIS e tu ricevi una notifica immediata.',
    route: '/dashboard/presidente/impianti',
    targetSelector: "[data-onboarding='section-ticket-urgenti']",
    guideText: 'Qui compaiono i ticket urgenti segnalati dal custode. I guasti critici ti arrivano come notifica push in tempo reale, anche quando non sei in sede.',
  },
  {
    id: 'pagamenti',
    title: 'Pagamenti e Incassi',
    problem: 'Riesci a vedere a colpo d\'occhio quante rate sono state incassate questo mese?',
    solution: 'ClubIS mostra tutti i movimenti in entrata e uscita con saldo aggiornato in tempo reale.',
    route: '/dashboard/presidente/pagamenti',
    targetSelector: "[data-onboarding='btn-nuovo-pagamento']",
    guideText: "Clicca '+ Nuovo movimento' per registrare un incasso o un'uscita. La dashboard si aggiorna istantaneamente con il nuovo saldo.",
  },
  {
    id: 'rendiconto',
    title: 'Rendiconto Entrate/Uscite',
    problem: 'Sai sempre in quale categoria il club spende di più rispetto al budget previsto?',
    solution: 'ClubIS suddivide entrate e uscite per categoria con grafici immediati.',
    route: '/dashboard/presidente/finanze',
    targetSelector: "[data-onboarding='section-rendiconto']",
    guideText: 'Qui vedi il dettaglio di ogni categoria finanziaria: quanto è entrato, quanto è uscito e il saldo netto del periodo selezionato.',
  },
  {
    id: 'ffp',
    title: 'FFP / Budget',
    problem: 'Sei certo che il tuo club rispetti i parametri del Fair Play Finanziario questa stagione?',
    solution: 'ClubIS calcola l\'indice FFP automaticamente e ti avvisa se esci dai parametri.',
    route: '/dashboard/presidente/ffp',
    targetSelector: "[data-onboarding='section-ffp-banner']",
    guideText: 'Questo indicatore mostra il rapporto uscite/entrate. Verde = FFP rispettato. Rosso = attenzione: le uscite superano le entrate. Clicca per il dettaglio per categoria.',
  },
  {
    id: 'budget-stagionale',
    title: 'Budget Stagionale',
    problem: 'Hai un piano di budget formale per la stagione o gestisci tutto a sensazione?',
    solution: 'ClubIS permette di pianificare entrate e uscite per categoria mese per mese.',
    route: '/dashboard/presidente/budget-stagionale',
    targetSelector: "[data-onboarding='btn-aggiungi-budget-entrata']",
    guideText: "Clicca '+ Aggiungi' nella sezione Entrate previste per inserire una voce di budget (es. sponsor, quote iscrizione). Fai lo stesso per le Uscite. Il sistema calcola il saldo previsionale.",
  },
  {
    id: 'disponibilita-rosa',
    title: 'Disponibilità Rosa',
    problem: 'Devi chiamare l\'allenatore per sapere quanti giocatori sono disponibili per la prossima partita?',
    solution: 'ClubIS mostra in tempo reale chi è disponibile, infortunato o squalificato.',
    route: '/dashboard/presidente/disponibilita',
    targetSelector: "[data-onboarding='section-disponibilita-rosa']",
    guideText: 'Qui vedi lo stato di ogni giocatore per la settimana corrente: disponibile, infortunato o squalificato. Il semaforo verde/giallo/rosso ti dà la situazione a colpo d\'occhio.',
  },
  {
    id: 'organigramma',
    title: 'Organigramma',
    problem: 'I nuovi collaboratori del club sanno a chi rivolgersi per ogni questione?',
    solution: 'ClubIS visualizza l\'organigramma del club con ruoli e responsabilità di ciascuno.',
    route: '/dashboard/presidente/organigramma',
    targetSelector: "[data-onboarding='btn-modifica-organigramma']",
    guideText: "Clicca 'Modifica organigramma' per aggiungere o aggiornare i ruoli del club. L'organigramma è visibile a tutti i collaboratori nella loro dashboard.",
  },
  {
    id: 'info-club',
    title: 'Info Club',
    problem: 'I dati ufficiali del club (ragione sociale, codice fiscale, logo) sono sempre aggiornati ovunque?',
    solution: 'ClubIS centralizza tutte le informazioni del club in un unico profilo aggiornabile.',
    route: '/dashboard/presidente/club',
    targetSelector: "[data-onboarding='btn-modifica-club']",
    guideText: "Clicca 'Modifica' per aggiornare i dati ufficiali del club: ragione sociale, colori sociali, logo, sede legale e contatti. Questi dati vengono usati automaticamente su documenti e comunicazioni.",
  },
  {
    id: 'compliance',
    title: 'Compliance Campionato',
    problem: 'Sai sempre se il club è in regola con tutti i requisiti di iscrizione al campionato?',
    solution: 'ClubIS verifica automaticamente ogni requisito e ti indica cosa manca.',
    route: '/dashboard/presidente/compliance-campionato',
    targetSelector: "[data-onboarding='section-compliance']",
    guideText: 'La barra di progresso mostra quanti requisiti del campionato sono soddisfatti. I requisiti in rosso richiedono attenzione immediata. Clicca su ognuno per vedere cosa fare.',
  },
]

const ONBOARDING_DS: OnboardingStep[] = [
  {
    id: 'rosa',
    title: 'Gestione Rosa',
    problem: 'Devi aprire più file Excel per avere il quadro completo della tua rosa per reparto?',
    solution: 'ClubIS mostra la rosa completa con filtri per reparto, stranieri e prestiti in tempo reale.',
    route: '/dashboard/ds/rosa',
    targetSelector: "[data-onboarding='btn-aggiungi-giocatore-ds']",
    guideText: 'Usa i KPI in alto per monitorare stranieri, prestiti ed età media. Clicca su un giocatore per aprire la sua scheda completa con contratto, statistiche e valutazioni.',
  },
  {
    id: 'contratti',
    title: 'Contratti',
    problem: 'Rischi di scoprire un contratto in scadenza solo quando è già troppo tardi per rinnovarlo?',
    solution: 'ClubIS monitora tutti i contratti e ti avvisa quando mancano meno di 90 giorni alla scadenza.',
    route: '/dashboard/ds/contratti',
    targetSelector: "[data-onboarding='section-contratti-ds']",
    guideText: 'Questa sezione evidenzia tutti i contratti in scadenza nei prossimi 90 giorni con i giorni rimasti. Clicca su un contratto per registrare il rinnovo o la cessazione.',
  },
  {
    id: 'scouting',
    title: 'Scouting e Osservazione',
    problem: 'I report degli osservatori ti arrivano su WhatsApp o su carta, senza un formato standard?',
    solution: 'ClubIS raccoglie tutti i report in un archivio strutturato con voti, potenziale e note.',
    route: '/dashboard/ds/scouting',
    targetSelector: "[data-onboarding='btn-nuovo-report-scouting']",
    guideText: 'Qui trovi tutti i report prodotti dagli osservatori. Filtra per esito (in valutazione, ingaggiato, archiviato) e clicca su un giocatore per vedere tutti i dettagli della valutazione.',
  },
  {
    id: 'mercato',
    title: 'Trattative di Mercato',
    problem: 'Le trattative di mercato vengono gestite via email e telefono senza uno storico consultabile?',
    solution: 'ClubIS traccia ogni trattativa con stato, importo e contatti, dando al presidente un quadro chiaro.',
    route: '/dashboard/ds/mercato',
    targetSelector: "[data-onboarding='btn-nuova-trattativa']",
    guideText: "Clicca '+ Nuova trattativa' per registrare un'operazione di mercato. Specifica giocatore, club, tipo (acquisto/cessione/prestito) e importo. Il presidente vedrà la pipeline aggiornata.",
  },
  {
    id: 'budget-mercato',
    title: 'Budget Mercato',
    problem: 'Sai in tempo reale quante risorse hai ancora disponibili per il mercato?',
    solution: 'ClubIS mostra il budget assegnato, speso e residuo per la sessione di mercato in corso.',
    route: '/dashboard/ds/budget-mercato',
    targetSelector: "[data-onboarding='section-budget-mercato']",
    guideText: 'Qui trovi il riepilogo del budget di mercato per stagione. Il grafico mostra la distribuzione delle spese per reparto. Usa questi dati quando presenti le tue proposte di acquisto al presidente.',
  },
  {
    id: 'database',
    title: 'Database Giocatori',
    problem: 'Hai profili di giocatori sparsi su fogli Excel, email e app diverse senza un archivio unico?',
    solution: 'ClubIS aggrega automaticamente tutti i report scouting in un database unico con filtri per ruolo e potenziale.',
    route: '/dashboard/ds/database',
    targetSelector: "[data-onboarding='btn-nuova-osservazione-db']",
    guideText: "Clicca '+ Nuova osservazione' per aggiungere un giocatore al database. Ogni profilo raccoglie tutti i report degli osservatori. Filtra per potenziale per identificare i migliori target di mercato.",
  },
  {
    id: 'scadenze',
    title: 'Scadenze Contrattuali',
    problem: 'Le scadenze di contratti, prestiti e opzioni le tieni in testa o su un foglio Excel?',
    solution: 'ClubIS aggrega in automatico tutte le scadenze contrattuali con un alert visivo per quelle urgenti.',
    route: '/dashboard/ds/scadenze',
    targetSelector: "[data-onboarding='section-scadenze-ds']",
    guideText: 'Questa pagina mostra contratti, prestiti e opzioni in scadenza nei prossimi 90 giorni ordinati per urgenza. Il badge rosso indica scadenza entro 14 giorni. Agisci prima che sia troppo tardi.',
  },
  {
    id: 'statistiche',
    title: 'Statistiche DS',
    problem: 'Per presentare i numeri della rosa al presidente devi raccogliere dati da fonti diverse?',
    solution: 'ClubIS genera automaticamente report su composizione rosa, rendimento e scouting pronti per le riunioni.',
    route: '/dashboard/ds/statistiche',
    targetSelector: "[data-onboarding='section-statistiche-ds']",
    guideText: 'Questa pagina aggrega automaticamente età media, stranieri, contratti in scadenza e rendimento per reparto. Usa i grafici per preparare le presentazioni alla presidenza.',
  },
  {
    id: 'disponibilita',
    title: 'Disponibilità Giocatori',
    problem: 'Non sai in tempo reale quali giocatori sono disponibili per la prossima gara?',
    solution: 'ClubIS mostra la disponibilità aggiornata di tutta la rosa con infortuni, squalifiche e convocazioni.',
    route: '/dashboard/ds/disponibilita',
    targetSelector: "[data-onboarding='section-disponibilita-ds']",
    guideText: 'Questa vista mostra la disponibilità di ogni giocatore per la settimana corrente. I colori indicano: verde disponibile, rosso infortunato, ambra in dubbio. Condividi queste informazioni con l\'allenatore.',
  },
]

const ONBOARDING_ALLENATORE: OnboardingStep[] = [
  {
    id: 'squadra',
    title: 'Gestione Squadra',
    problem: 'Per sapere le presenze e le statistiche dei tuoi giocatori devi andare da qualcuno o cercare su un foglio?',
    solution: 'ClubIS mostra la lista della squadra con percentuale presenze e ultime valutazioni sempre aggiornate.',
    route: '/dashboard/allenatore/rosa',
    targetSelector: "[data-onboarding='lista-giocatori']",
    guideText: "Ogni giocatore mostra il ruolo, la percentuale di presenze e l'ultima valutazione tecnica. Clicca su un giocatore per aprire la sua scheda completa.",
  },
  {
    id: 'presenze',
    title: 'Registro Presenze',
    problem: 'Segni ancora le presenze agli allenamenti su un foglio di carta che poi perdi?',
    solution: 'ClubIS registra le presenze digitalmente in due minuti direttamente dal tuo telefono.',
    route: '/dashboard/allenatore/presenze',
    targetSelector: "[data-onboarding='btn-nuova-sessione']",
    guideText: "Clicca '+ Nuova sessione' per creare un allenamento. Poi seleziona la sessione e tocca ogni giocatore per segnarlo presente o assente. Le presenze vengono salvate automaticamente.",
  },
  {
    id: 'convocazioni',
    title: 'Convocazioni',
    problem: 'Mandi ancora le convocazioni su WhatsApp e poi non sai chi ha confermato?',
    solution: 'ClubIS invia le convocazioni in-app e traccia le risposte di ogni giocatore.',
    route: '/dashboard/allenatore/convocazioni',
    targetSelector: "[data-onboarding='btn-nuova-convocazione']",
    guideText: "Clicca '+ Nuova convocazione', seleziona la partita e spunta i giocatori convocati. Ogni giocatore riceve una notifica e può confermare o declinare direttamente dall'app.",
  },
  {
    id: 'valutazioni',
    title: 'Valutazioni Tecniche',
    problem: 'Come dai un feedback strutturato ai tuoi giocatori sulla loro crescita tecnica?',
    solution: 'ClubIS ti permette di valutare ogni giocatore su 4 aree e condividere il voto con la famiglia.',
    route: '/dashboard/allenatore/valutazioni',
    targetSelector: "[data-onboarding='btn-nuova-valutazione']",
    guideText: 'Seleziona un giocatore e assegna un voto da 1 a 10 per tecnica, tattica, fisico e mentalità. Aggiungi una nota. Scegli se rendere la valutazione visibile alla famiglia.',
  },
  {
    id: 'tattica',
    title: 'Schema Tattico',
    problem: 'Disegni ancora i moduli di gioco su carta o su una lavagna che poi non rimane da nessuna parte?',
    solution: 'ClubIS ha un campo interattivo dove posizioni i giocatori con drag-and-drop e salvi la formazione.',
    route: '/dashboard/allenatore/tattica',
    targetSelector: "[data-onboarding='campo-tattico']",
    guideText: "Seleziona il modulo dal menu (4-3-3, 4-4-2, 3-5-2...) e trascina i giocatori nelle loro posizioni. Salva la formazione per usarla nelle convocazioni e nelle distinte.",
  },
  {
    id: 'statistiche',
    title: 'Statistiche Giocatori',
    problem: 'Sai sempre chi sono i giocatori più continui della stagione e chi sta calando di rendimento?',
    solution: 'ClubIS aggrega tutte le statistiche individuali in tempo reale per l\'intera stagione.',
    route: '/dashboard/allenatore/statistiche',
    targetSelector: "[data-onboarding='tabella-statistiche']",
    guideText: 'Qui vedi gol, assist, presenze, ammonizioni ed espulsioni di ogni giocatore. Ordina la tabella per qualsiasi colonna per trovare subito chi performa meglio.',
  },
]

const ONBOARDING_OSSERVATORE: OnboardingStep[] = [
  {
    id: 'nuovo-report',
    title: 'Report di Scouting',
    problem: 'I tuoi report di osservazione finiscono su carta o su note del telefono senza un formato standard?',
    solution: 'ClubIS ha un modulo strutturato per ogni osservazione, con voti, potenziale e export PDF immediato.',
    route: '/dashboard/osservatore/nuovo-report',
    targetSelector: "[data-onboarding='btn-nuovo-report']",
    guideText: "Clicca '+ Nuovo report' per iniziare un'osservazione. Inserisci nome del giocatore, club, data e luogo. Poi assegna i voti per area e scrivi punti di forza e debolezze.",
  },
  {
    id: 'export-pdf',
    title: 'Export PDF Report',
    problem: 'Come presenti un giocatore al DS in modo professionale senza perdere tempo a formattare un documento?',
    solution: 'ClubIS esporta il report in PDF professionale pronto per la presentazione in un click.',
    route: '/dashboard/osservatore/report',
    targetSelector: "[data-onboarding='btn-export-pdf']",
    guideText: "Apri un report già completato e clicca 'Esporta PDF'. Il documento è formattato con tutti i dati, i voti per area e le note. Pronto da inviare al DS o al presidente.",
  },
  {
    id: 'confronto',
    title: 'Confronto Giocatori',
    problem: 'Come decidi quale tra due giocatori osservati proporre al DS senza basarti solo sull\'intuito?',
    solution: 'ClubIS affianca i profili di due o più giocatori su ogni parametro valutato.',
    route: '/dashboard/osservatore/confronto',
    targetSelector: "[data-onboarding='btn-confronta']",
    guideText: 'Seleziona due giocatori dalla lista e clicca \'Confronta\'. Vedi tecnica, tattica, fisico e mentalità fianco a fianco. Le differenze sono evidenziate visivamente.',
  },
  {
    id: 'mappa',
    title: 'Mappa Osservazioni',
    problem: 'Sai da quali zone geografiche stai portando più segnalazioni? Stai coprendo il territorio in modo efficiente?',
    solution: 'ClubIS mostra sulla mappa dove si concentra la tua attività di scouting.',
    route: '/dashboard/osservatore/mappa',
    targetSelector: "[data-onboarding='mappa-scouting']",
    guideText: 'Questa mappa visualizza tutte le tue osservazioni geograficamente. Usa i filtri per vedere solo i giocatori in valutazione o quelli ingaggiati.',
  },
  {
    id: 'statistiche-personali',
    title: 'Le tue Statistiche',
    problem: 'Sai quanti giocatori hai segnalato e quanti sono stati effettivamente ingaggiati dal club?',
    solution: 'ClubIS monitora il tuo tasso di conversione e l\'impatto delle tue segnalazioni.',
    route: '/dashboard/osservatore/statistiche',
    targetSelector: "[data-onboarding='section-stats-osservatore']",
    guideText: 'Qui trovi il totale dei report creati, i giocatori ingaggiati grazie alle tue segnalazioni e il tasso di conversione. Una panoramica del tuo lavoro stagionale.',
  },
]

const ONBOARDING_FAMIGLIA: OnboardingStep[] = [
  {
    id: 'profilo-figlio',
    title: 'Profilo del Figlio',
    problem: 'Come tieni traccia delle informazioni sportive di tuo figlio senza chiamare il club ogni volta?',
    solution: 'ClubIS ti dà accesso al profilo completo di tuo figlio sempre aggiornato.',
    route: '/dashboard/famiglia',
    targetSelector: "[data-onboarding='card-profilo-figlio']",
    guideText: 'Qui trovi tutti i dati di tuo figlio: ruolo, età, tessera FIGC e foto. Le informazioni vengono aggiornate dalla segreteria.',
  },
  {
    id: 'presenze',
    title: 'Presenze agli Allenamenti',
    problem: 'Non sai mai con certezza quante volte tuo figlio ha partecipato agli allenamenti questo mese?',
    solution: 'ClubIS mostra la percentuale di presenze aggiornata in tempo reale.',
    route: '/dashboard/famiglia',
    targetSelector: "[data-onboarding='section-presenze-figlio']",
    guideText: 'Qui vedi la percentuale di presenze agli allenamenti degli ultimi 30 giorni. L\'indicatore diventa rosso se la partecipazione scende sotto la soglia.',
  },
  {
    id: 'valutazioni',
    title: 'Valutazioni del Coach',
    problem: 'Non ricevi mai un feedback strutturato dall\'allenatore sulla crescita di tuo figlio?',
    solution: 'ClubIS ti mostra le valutazioni tecniche condivise dall\'allenatore con voti per ogni area.',
    route: '/dashboard/famiglia',
    targetSelector: "[data-onboarding='section-valutazioni-figlio']",
    guideText: "Quando l'allenatore decide di condividere una valutazione, la trovi qui con i voti per tecnica, tattica, fisico e mentalità, più le note personali del coach.",
  },
  {
    id: 'pagamenti',
    title: 'Quote e Pagamenti',
    problem: 'Non sai mai esattamente quanto hai pagato e quanto devi ancora versare al club?',
    solution: 'ClubIS mostra la situazione aggiornata della quota con le rate future e le scadenze.',
    route: '/dashboard/famiglia/pagamenti',
    targetSelector: "[data-onboarding='section-pagamenti-figlio']",
    guideText: 'Qui vedi l\'importo totale, quanto è già stato pagato (con la barra di progresso) e le prossime rate con le relative scadenze. Riceverai un avviso prima di ogni scadenza.',
  },
  {
    id: 'calendario',
    title: 'Calendario',
    problem: 'Devi sempre chiedere al club o cercare su WhatsApp gli orari delle partite e degli allenamenti?',
    solution: 'ClubIS mostra il calendario completo della squadra di tuo figlio sempre aggiornato.',
    route: '/dashboard/famiglia/calendario',
    targetSelector: "[data-onboarding='sezione-calendario']",
    guideText: 'Qui trovi partite e allenamenti in ordine cronologico, con data, orario e luogo. Il calendario si aggiorna automaticamente quando il club fa modifiche.',
  },
]

const ONBOARDING_MEDICO: OnboardingStep[] = [
  {
    id: 'cartelle-mediche',
    title: 'Cartelle Mediche',
    problem: 'Le cartelle mediche dei giocatori sono su carta o in archivi non condivisi con il club?',
    solution: 'ClubIS centralizza tutte le cartelle mediche: anamnesi, infortuni, terapie e idoneità in un unico posto sicuro.',
    route: '/dashboard/medico/cartelle',
    targetSelector: "[data-onboarding='section-cartelle']",
    guideText: "Qui trovi la lista di tutti i giocatori con la loro scheda sanitaria. Clicca su 'Apri cartella' per vedere o aggiornare anamnesi, allergie e annotazioni cliniche di ogni atleta.",
  },
  {
    id: 'certificati',
    title: 'Certificati Idoneità',
    problem: 'Tieni traccia delle scadenze dei certificati di idoneità su fogli separati e rischi dimenticanze?',
    solution: 'ClubIS monitora la scadenza di ogni certificato e ti avvisa in anticipo con un alert automatico.',
    route: '/dashboard/medico/certificati',
    targetSelector: "[data-onboarding='btn-nuovo-certificato']",
    guideText: "Qui vedi tutti i certificati con la data di scadenza. Il semaforo verde/giallo/rosso ti indica immediatamente quali stanno per scadere. Clicca per aggiungerne uno nuovo.",
  },
  {
    id: 'infortuni',
    title: 'Gestione Infortuni',
    problem: 'Quando un giocatore si infortuna, le informazioni vengono comunicate in modo frammentato via WhatsApp?',
    solution: 'ClubIS registra ogni infortunio con diagnosi, terapia e prognosi, condivisibile con allenatore e DS in un clic.',
    route: '/dashboard/medico/infortuni',
    targetSelector: "[data-onboarding='btn-nuovo-infortunio']",
    guideText: "Clicca '+ Nuovo infortunio' per registrare il tipo di trauma, la diagnosi e la prognosi in giorni. L'allenatore vedrà automaticamente il giocatore come non disponibile.",
  },
  {
    id: 'visite',
    title: 'Visite Mediche',
    problem: 'La programmazione delle visite di controllo avviene ancora tramite telefonate e appunti cartacei?',
    solution: 'ClubIS gestisce il calendario delle visite mediche con promemoria automatici per staff e giocatori.',
    route: '/dashboard/medico/visite',
    targetSelector: "[data-onboarding='btn-nuova-visita']",
    guideText: "Programma qui le visite di controllo periodiche. Ogni visita genera un promemoria automatico al giocatore e compare nel calendario del medico.",
  },
]

const ONBOARDING_TEAM_MANAGER: OnboardingStep[] = [
  {
    id: 'convocazioni',
    title: 'Convocazioni',
    problem: 'Gestisci ancora le convocazioni tramite messaggi WhatsApp e rischi che qualcuno non li legga?',
    solution: 'ClubIS invia le convocazioni direttamente nell\'app e tiene traccia di chi ha confermato.',
    route: '/dashboard/team-manager/convocazioni',
    targetSelector: "[data-onboarding='btn-nuova-convocazione']",
    guideText: "Clicca '+ Nuova convocazione' per selezionare i giocatori, l'orario di ritrovo e il luogo. Ogni giocatore riceverà una notifica e potrà confermare la presenza.",
  },
  {
    id: 'trasferte',
    title: 'Gestione Trasferte',
    problem: 'La logistica delle trasferte viene organizzata con messaggi sparsi e senza un riepilogo unico?',
    solution: 'ClubIS centralizza trasporti, alloggi e costi di ogni trasferta in un unico documento condivisibile.',
    route: '/dashboard/team-manager/trasferte',
    targetSelector: "[data-onboarding='btn-nuova-trasferta']",
    guideText: "Clicca '+ Nuova trasferta' per inserire partita, mezzo di trasporto, punto di ritrovo e costi previsti. Lo staff vedrà tutto in tempo reale.",
  },
  {
    id: 'materiale',
    title: 'Materiale Sportivo',
    problem: 'Non sai mai con precisione quante divise o palloni sono disponibili e in che stato sono?',
    solution: 'ClubIS tiene il magazzino del materiale sportivo con quantità, stato e chi lo ha in uso.',
    route: '/dashboard/team-manager/materiale',
    targetSelector: "[data-onboarding='btn-aggiungi-materiale']",
    guideText: "Aggiungi qui ogni articolo del magazzino: nome, quantità e stato (nuovo/usato/da riparare). Potrai sapere in ogni momento cosa è disponibile e cosa manca.",
  },
  {
    id: 'presenze-allenamento',
    title: 'Presenze Allenamenti',
    problem: 'Tieni le presenze agli allenamenti su carta o in un foglio Excel che poi si perde?',
    solution: 'ClubIS permette di registrare le presenze in pochi tap direttamente dallo spogliatoio.',
    route: '/dashboard/team-manager/presenze-allenamento',
    targetSelector: "[data-onboarding='section-presenze']",
    guideText: "Seleziona la data e spunta i presenti. Il sistema calcola automaticamente le percentuali di presenza per ogni giocatore e le rende disponibili all'allenatore.",
  },
  {
    id: 'accrediti-tm',
    title: 'Accrediti Stadio',
    problem: 'Gestisci ancora le liste accrediti per le gare via email o carta stampata?',
    solution: 'ClubIS centralizza media, VIP e ospiti con una lista digitale per ogni partita.',
    route: '/dashboard/team-manager/accrediti',
    targetSelector: "[data-onboarding='section-accrediti-tm']",
    guideText: "Seleziona la partita e aggiungi le persone accreditate: giornalisti, sponsor, familiari VIP. La lista è disponibile al controllo accessi in tempo reale direttamente dallo smartphone.",
  },
  {
    id: 'inviti-staff',
    title: 'Inviti Staff',
    problem: 'Per aggiungere un nuovo membro allo staff devi chiedere all\'amministratore di sistema?',
    solution: 'ClubIS ti permette di generare link di invito per ogni ruolo staff in autonomia.',
    route: '/dashboard/team-manager/inviti',
    targetSelector: "[data-onboarding='section-inviti-staff']",
    guideText: "Seleziona il ruolo (es. allenatore, medico, ufficio stampa), imposta la scadenza del link e copialo. Il nuovo membro si registra autonomamente e viene collegato al tuo club.",
  },
  {
    id: 'pagamenti-tm',
    title: 'Pagamenti e Finanze',
    problem: 'Non hai visibilità sulle entrate e uscite del club senza dover chiedere alla segreteria?',
    solution: 'ClubIS ti mostra la prima nota del club con tutti i movimenti in entrata e uscita.',
    route: '/dashboard/team-manager/pagamenti',
    targetSelector: "[data-onboarding='btn-nuovo-movimento-tm']",
    guideText: "Clicca '+ Nuovo movimento' per registrare un'entrata o un'uscita. Seleziona la categoria, l'importo e la data. I dati sono condivisi con presidenza e segreteria.",
  },
  {
    id: 'rosa-figc',
    title: 'Rosa FIGC',
    problem: 'Compili manualmente i moduli di schieramento su carta prima di ogni gara?',
    solution: 'ClubIS genera la rosa FIGC con il modulo di campo interattivo che puoi adattare per ogni partita.',
    route: '/dashboard/segretario/figc/rosa',
    targetSelector: "[data-onboarding='campo-figc']",
    guideText: "Trascina i giocatori nella posizione desiderata sul campo. Il sistema genera automaticamente il modulo ufficiale FIGC con i dati aggiornati del tesseramento.",
  },
  {
    id: 'moduli-figc',
    title: 'Moduli FIGC',
    problem: 'Compili i moduli federali di infortunio, svincolo e affiliazione a mano su carta?',
    solution: 'ClubIS compila i moduli FIGC in automatico con i dati già presenti nel sistema.',
    route: '/dashboard/segretario/figc/moduli',
    targetSelector: "[data-onboarding='section-moduli-figc']",
    guideText: "Seleziona il tipo di modulo (infortuni, svincolo, affiliazione), scegli il giocatore e ClubIS precompila tutti i campi con i dati del tesseramento. Stampa o scarica il PDF direttamente.",
  },
]

const ONBOARDING_UFFICIO_STAMPA: OnboardingStep[] = [
  {
    id: 'articoli',
    title: 'Articoli e Comunicati',
    problem: 'Pubblichi comunicati e notizie del club su piattaforme diverse senza un archivio organizzato?',
    solution: 'ClubIS centralizza tutti gli articoli e comunicati del club in un unico archivio professionale.',
    route: '/dashboard/ufficio-stampa/articoli',
    targetSelector: "[data-onboarding='btn-nuovo-articolo']",
    guideText: "Clicca '+ Nuovo articolo' per creare un comunicato. Puoi inserire titolo, testo, immagini e tag. Ogni articolo viene salvato nell'archivio del club.",
  },
  {
    id: 'interviste',
    title: 'Interviste',
    problem: 'Le interviste a giocatori e staff finiscono sparse in cartelle disorganizzate sul computer?',
    solution: 'ClubIS archivia tutte le interviste con data, soggetto e media di riferimento, sempre trovabili.',
    route: '/dashboard/ufficio-stampa/interviste',
    targetSelector: "[data-onboarding='btn-nuova-intervista']",
    guideText: "Aggiungi qui ogni intervista: chi l'ha rilasciata, quale testata, e il testo o il link al video. L'archivio è consultabile da tutti i membri dello staff autorizzati.",
  },
  {
    id: 'accrediti',
    title: 'Accrediti Stampa',
    problem: 'Gestisci le richieste di accredito stampa per le partite ancora via email o telefono?',
    solution: 'ClubIS centralizza gli accrediti stampa per ogni partita con lista giornalisti e fotografi.',
    route: '/dashboard/ufficio-stampa/accrediti',
    targetSelector: "[data-onboarding='section-accrediti']",
    guideText: "Seleziona la partita e aggiungi gli accrediti per i giornalisti. Puoi specificare tipo (stampa, TV, foto) e il nominativo. La lista è sempre disponibile al controllo accessi.",
  },
  {
    id: 'locandine',
    title: 'Locandine e Grafica',
    problem: 'Le locandine delle partite vengono create e inviate senza un archivio storico consultabile?',
    solution: 'ClubIS archivia tutte le locandine e i materiali grafici del club in ordine cronologico.',
    route: '/dashboard/ufficio-stampa/locandine',
    targetSelector: "[data-onboarding='btn-nuova-locandina']",
    guideText: "Carica qui le locandine delle partite e gli altri materiali grafici. Vengono salvati con la data e la partita di riferimento per un archivio sempre in ordine.",
  },
]

const ONBOARDING_CUSTODE: OnboardingStep[] = [
  {
    id: 'impianti',
    title: 'Gestione Impianti',
    problem: 'Tieni traccia delle manutenzioni e delle anomalie dell\'impianto su carta o a memoria?',
    solution: 'ClubIS centralizza tutte le segnalazioni e le manutenzioni dell\'impianto sportivo in un registro digitale.',
    route: '/dashboard/custode/impianti',
    targetSelector: "[data-onboarding='section-impianti']",
    guideText: "Clicca per registrare una nuova segnalazione o intervento di manutenzione. Specifica l'area dell'impianto, il tipo di problema e la priorità. Lo staff di riferimento verrà notificato.",
  },
]

const ONBOARDING_GIOCATORE: OnboardingStep[] = [
  {
    id: 'convocazioni',
    title: 'Le tue Convocazioni',
    problem: 'Scopri in ritardo le convocazioni perché arrivano via WhatsApp e non le vedi subito?',
    solution: 'ClubIS ti mostra le convocazioni direttamente nell\'app con notifica istantanea.',
    route: '/dashboard/giocatore/convocazioni',
    targetSelector: "[data-onboarding='sezione-convocazioni']",
    guideText: "Qui trovi tutte le convocazioni per le partite. Puoi vedere data, orario di ritrovo, luogo e confermare la tua presenza con un tocco.",
  },
  {
    id: 'statistiche',
    title: 'Le tue Statistiche',
    problem: 'Non hai mai un riepilogo chiaro dei tuoi gol, assist e minuti giocati stagione per stagione?',
    solution: 'ClubIS tiene il tuo storico completo con tutte le statistiche aggiornate dopo ogni partita.',
    route: '/dashboard/giocatore/statistiche',
    targetSelector: "[data-onboarding='sezione-statistiche']",
    guideText: "Qui trovi le tue statistiche della stagione: gol, assist, presenze e minuti giocati. I dati vengono aggiornati dallo staff dopo ogni partita.",
  },
  {
    id: 'pagamenti',
    title: 'Quote e Pagamenti',
    problem: 'Non sai mai con precisione quanto hai pagato e quanto ti resta da versare per la stagione?',
    solution: 'ClubIS mostra la tua situazione pagamenti in tempo reale, con storico e rate future.',
    route: '/dashboard/giocatore/pagamenti',
    targetSelector: "[data-onboarding='sezione-pagamenti']",
    guideText: "Qui trovi la tua quota iscrizione, i pagamenti già effettuati e le rate ancora da versare. In caso di dubbi puoi contattare direttamente la segreteria dal pannello.",
  },
]

export const ONBOARDING_STEPS: Record<string, OnboardingStep[]> = {
  segretario: ONBOARDING_SEGRETARIO,
  presidente: ONBOARDING_PRESIDENTE,
  direttore_sportivo: ONBOARDING_DS,
  allenatore: ONBOARDING_ALLENATORE,
  osservatore: ONBOARDING_OSSERVATORE,
  famiglia: ONBOARDING_FAMIGLIA,
  medico: ONBOARDING_MEDICO,
  team_manager: ONBOARDING_TEAM_MANAGER,
  ufficio_stampa: ONBOARDING_UFFICIO_STAMPA,
  custode: ONBOARDING_CUSTODE,
  giocatore: ONBOARDING_GIOCATORE,
}
