export interface OnboardingStep {
  id: string
  title: string
  problem: string
  solution: string
  route: string
  targetSelector: string
  guideText: string
}

const ONBOARDING_SEGRETARIO: OnboardingStep[] = [
  {
    id: 'anagrafica',
    title: 'Gestione Anagrafica',
    problem: 'Hai i dati dei giocatori su fogli Excel, WhatsApp e foglietti di carta separati?',
    solution: 'Con ClubIS hai tutti i giocatori in un unico archivio digitale, sempre aggiornato.',
    route: '/dashboard/segretario/giocatori',
    targetSelector: "[data-onboarding='btn-aggiungi-giocatore']",
    guideText: "Clicca '+ Aggiungi giocatore' per inserire il primo giocatore. Puoi anche importare una lista intera da Excel con un solo file CSV.",
  },
  {
    id: 'tesseramenti',
    title: 'Tesseramenti',
    problem: 'Sai sempre quanti giocatori sono in prestito e quanti tesserati definitivamente?',
    solution: 'ClubIS tiene traccia di ogni tipo di tesseramento con lo stato aggiornato in tempo reale.',
    route: '/dashboard/segretario/tesseramenti',
    targetSelector: "[data-onboarding='btn-nuovo-tesseramento']",
    guideText: "Clicca '+ Nuovo tesseramento' e seleziona il tipo: definitivo, prestito, prova, svincolo. Il codice tessera FIGC viene registrato automaticamente.",
  },
  {
    id: 'certificati',
    title: 'Certificati Medici',
    problem: 'Ti è già capitato di scoprire un certificato scaduto la sera prima di una partita?',
    solution: 'ClubIS ti avvisa in automatico quando un certificato sta per scadere, con 30 giorni e 7 giorni di anticipo.',
    route: '/dashboard/segretario/certificati',
    targetSelector: "[data-onboarding='section-certificati-scadenza']",
    guideText: "Questa sezione mostra tutti i certificati in scadenza nei prossimi 30 giorni. Clicca 'Rinnova' direttamente dalla lista senza reinserire i dati.",
  },
  {
    id: 'partite',
    title: 'Calendario Partite',
    problem: 'Inserisci ancora le partite una per una a mano ogni stagione?',
    solution: 'ClubIS importa il calendario dal PDF ufficiale FIGC in pochi secondi.',
    route: '/dashboard/segretario/partite',
    targetSelector: "[data-onboarding='btn-importa-calendario']",
    guideText: "Clicca 'Importa da PDF' per caricare il calendario ufficiale della FIGC. Tutte le partite vengono create automaticamente. Puoi anche aggiungerne una singola con '+ Nuova partita'.",
  },
  {
    id: 'distinte',
    title: 'Distinte Gara',
    problem: 'Quanto tempo perdi ogni settimana a compilare la distinta su carta prima di ogni partita?',
    solution: 'ClubIS genera la distinta ufficiale pronta per la stampa in 30 secondi.',
    route: '/dashboard/segretario/distinte',
    targetSelector: "[data-onboarding='btn-genera-distinta']",
    guideText: "Seleziona la partita, clicca 'Genera distinta' e scegli i convocati dalla lista. La distinta esce già formattata per il direttore di gara.",
  },
  {
    id: 'pagamenti',
    title: 'Quote e Pagamenti',
    problem: 'Rincorri ancora le famiglie con messaggi su WhatsApp per le quote non pagate?',
    solution: 'ClubIS mostra chi non ha pagato e invia i solleciti direttamente dal sistema.',
    route: '/dashboard/segretario/pagamenti',
    targetSelector: "[data-onboarding='section-arretrati']",
    guideText: "Qui vedi il totale degli arretrati e chi è in ritardo. Clicca 'Sollecita' accanto a un giocatore per inviare un avviso direttamente in-app o via email.",
  },
  {
    id: 'prima-nota',
    title: 'Prima Nota',
    problem: 'Tieni le entrate e le uscite del club su un foglio Excel o, peggio, su carta?',
    solution: 'ClubIS registra ogni movimento e calcola il saldo del club in tempo reale.',
    route: '/dashboard/segretario/prima-nota',
    targetSelector: "[data-onboarding='btn-nuova-entrata']",
    guideText: "Usa '+ Entrata' o '+ Uscita' per registrare ogni movimento. Seleziona la categoria, inserisci importo e descrizione. Il saldo si aggiorna istantaneamente.",
  },
  {
    id: 'figc',
    title: 'Conformità FIGC',
    problem: 'Passi 30 minuti a leggere ogni Comunicato Ufficiale FIGC per trovare le squalifiche dei tuoi giocatori?',
    solution: 'ClubIS legge il PDF del comunicato e applica le squalifiche ai giocatori con un click.',
    route: '/dashboard/segretario/figc/comunicati',
    targetSelector: "[data-onboarding='btn-carica-cu']",
    guideText: "Clicca 'Carica C.U.' e seleziona il PDF del Comunicato Ufficiale FIGC. Il sistema identifica automaticamente le squalifiche e le abbina ai giocatori della rosa. Approva con un click.",
  },
  {
    id: 'documenti',
    title: 'Libreria Documenti',
    problem: 'Crei ancora i contratti e le liberatorie da zero ogni volta con Word?',
    solution: 'ClubIS ha una libreria di modelli ufficiali che compila automaticamente con i dati del giocatore.',
    route: '/dashboard/segretario/documenti',
    targetSelector: "[data-onboarding='btn-genera-documento']",
    guideText: "Seleziona il tipo di documento dal catalogo (contratto, liberatoria, comunicazione...), scegli il giocatore e ClubIS compila tutti i campi in automatico. Stampa o salva in PDF.",
  },
  {
    id: 'sepa',
    title: 'Rimborsi SEPA',
    problem: 'Fai ancora i bonifici di rimborso uno per uno dalla tua banca online ogni mese?',
    solution: 'ClubIS genera il file XML SEPA per tutti i rimborsi del mese in un solo click.',
    route: '/dashboard/segretario/rimborsi',
    targetSelector: "[data-onboarding='btn-genera-sepa']",
    guideText: "Seleziona il mese di riferimento e clicca 'Genera file SEPA'. Il sistema crea automaticamente il file XML compatibile con la tua banca. Scaricalo e caricalo sul conto del club.",
  },
]

const ONBOARDING_PRESIDENTE: OnboardingStep[] = [
  {
    id: 'dashboard-kpi',
    title: 'Panoramica Esecutiva',
    problem: 'Devi chiamare il segretario o il DS ogni volta che vuoi sapere come sta andando il club?',
    solution: 'La tua dashboard mostra in tempo reale tutti i KPI del club: giocatori, finanze, partite.',
    route: '/dashboard/presidente',
    targetSelector: "[data-onboarding='section-kpi-overview']",
    guideText: 'Questa è la tua vista di controllo. Qui vedi giocatori tesserati, entrate del mese, quote arretrate e ultimi risultati. Tutto aggiornato in tempo reale senza chiedere a nessuno.',
  },
  {
    id: 'finanze',
    title: 'Finanze e Budget',
    problem: 'Sai sempre con precisione se il club sta rispettando il budget annuale?',
    solution: 'ClubIS monitora entrate, uscite e Financial Fair Play con grafici chiari.',
    route: '/dashboard/presidente/finanze',
    targetSelector: "[data-onboarding='section-budget-annuale']",
    guideText: "Qui trovi il budget annuale diviso per categoria. Il grafico mostra l'andamento mensile e l'indicatore FFP segnala subito se sei fuori dai parametri.",
  },
  {
    id: 'sponsor',
    title: 'Sponsor',
    problem: 'Hai ancora i contratti degli sponsor in una cartella su email o in un cassetto?',
    solution: 'ClubIS gestisce tutti gli sponsor con importi, tipologie e contributo totale.',
    route: '/dashboard/presidente/sponsor',
    targetSelector: "[data-onboarding='btn-aggiungi-sponsor']",
    guideText: "Clicca '+ Aggiungi sponsor' per registrare nome, categoria (gold/silver/bronze) e importo del contratto. Il totale dei contributi si aggiorna automaticamente.",
  },
  {
    id: 'staff',
    title: 'Staff e Organigramma',
    problem: 'I collaboratori del club sanno già usare ClubIS? Invitali in pochi secondi.',
    solution: 'ClubIS genera un link di invito personalizzato per ogni membro dello staff.',
    route: '/dashboard/presidente/inviti',
    targetSelector: "[data-onboarding='btn-invita-staff']",
    guideText: "Clicca 'Invita membro' e inserisci email e ruolo. Il collaboratore riceve un link di accesso e vede solo la sua dashboard dedicata.",
  },
  {
    id: 'obiettivi',
    title: 'Obiettivi Stagionali',
    problem: 'Gli obiettivi della stagione esistono solo nella tua testa o in un documento che nessuno aggiorna?',
    solution: 'ClubIS tiene traccia degli obiettivi stagionali e monitora i progressi nel tempo.',
    route: '/dashboard/presidente/obiettivi',
    targetSelector: "[data-onboarding='btn-nuovo-obiettivo']",
    guideText: "Definisci gli obiettivi sportivi e organizzativi della stagione. ClubIS aggiorna i progressi automaticamente man mano che arrivano i risultati.",
  },
  {
    id: 'report',
    title: 'Report Mensile',
    problem: 'Preparare il report per il consiglio direttivo ti porta via mezza giornata ogni mese?',
    solution: 'ClubIS genera il report mensile completo con tutti i KPI in un click.',
    route: '/dashboard/presidente/report',
    targetSelector: "[data-onboarding='btn-genera-report']",
    guideText: "Seleziona il mese e clicca 'Genera report'. Ottieni un documento completo con dati sportivi, economici e organizzativi, pronto per essere esportato e presentato.",
  },
  {
    id: 'impianti',
    title: 'Impianti',
    problem: 'Come vieni a sapere di un guasto urgente all\'impianto? Aspetti che qualcuno ti chiami?',
    solution: 'Il custode segnala i problemi su ClubIS e tu ricevi una notifica immediata.',
    route: '/dashboard/presidente/impianti',
    targetSelector: "[data-onboarding='section-ticket-urgenti']",
    guideText: 'Qui compaiono i ticket urgenti segnalati dal custode. I guasti critici ti arrivano come notifica push in tempo reale, anche quando non sei in sede.',
  },
]

const ONBOARDING_DS: OnboardingStep[] = [
  {
    id: 'rosa',
    title: 'Gestione Rosa',
    problem: 'Devi aprire più file Excel per avere il quadro completo della tua rosa per reparto?',
    solution: 'ClubIS mostra la rosa completa con filtri per reparto, stranieri e prestiti in tempo reale.',
    route: '/dashboard/ds/rosa',
    targetSelector: "[data-onboarding='filtri-reparto']",
    guideText: 'Usa i filtri in alto per vedere portieri, difensori, centrocampisti e attaccanti separatamente. Il badge mostra subito il numero di stranieri e giocatori in prestito.',
  },
  {
    id: 'contratti',
    title: 'Contratti',
    problem: 'Rischi di scoprire un contratto in scadenza solo quando è già troppo tardi per rinnovarlo?',
    solution: 'ClubIS monitora tutti i contratti e ti avvisa quando mancano meno di 90 giorni alla scadenza.',
    route: '/dashboard/ds/contratti',
    targetSelector: "[data-onboarding='section-contratti-scadenza']",
    guideText: 'Questa sezione evidenzia tutti i contratti in scadenza nei prossimi 90 giorni con i giorni rimasti. Clicca su un contratto per registrare il rinnovo o la cessazione.',
  },
  {
    id: 'scouting',
    title: 'Scouting e Osservazione',
    problem: 'I report degli osservatori ti arrivano su WhatsApp o su carta, senza un formato standard?',
    solution: 'ClubIS raccoglie tutti i report in un archivio strutturato con voti, potenziale e note.',
    route: '/dashboard/ds/scouting',
    targetSelector: "[data-onboarding='section-report-scouting']",
    guideText: 'Qui trovi tutti i report prodotti dagli osservatori. Filtra per esito (in valutazione, ingaggiato, archiviato) e clicca su un giocatore per vedere tutti i dettagli della valutazione.',
  },
  {
    id: 'mercato',
    title: 'Database e Mercato',
    problem: 'Quando valuti un giocatore, come confronti le offerte e i profili in modo oggettivo?',
    solution: 'ClubIS permette di confrontare fianco a fianco tutti i giocatori osservati su ogni parametro.',
    route: '/dashboard/ds/mercato',
    targetSelector: "[data-onboarding='btn-confronto-giocatori']",
    guideText: "Seleziona due o più giocatori osservati e clicca 'Confronta'. Vedi i voti per tecnica, tattica, fisico e mentalità in una tabella comparativa. Esporta il PDF per presentarlo al presidente.",
  },
]

const ONBOARDING_ALLENATORE: OnboardingStep[] = [
  {
    id: 'squadra',
    title: 'Gestione Squadra',
    problem: 'Per sapere le presenze e le statistiche dei tuoi giocatori devi andare da qualcuno o cercare su un foglio?',
    solution: 'ClubIS mostra la lista della squadra con percentuale presenze e ultime valutazioni sempre aggiornate.',
    route: '/dashboard/allenatore/rosa',
    targetSelector: "[data-onboarding='lista-giocatori']",
    guideText: "Ogni giocatore mostra il ruolo, la percentuale di presenze e l'ultima valutazione tecnica. Clicca su un giocatore per aprire la sua scheda completa.",
  },
  {
    id: 'presenze',
    title: 'Registro Presenze',
    problem: 'Segni ancora le presenze agli allenamenti su un foglio di carta che poi perdi?',
    solution: 'ClubIS registra le presenze digitalmente in due minuti direttamente dal tuo telefono.',
    route: '/dashboard/allenatore/presenze',
    targetSelector: "[data-onboarding='btn-nuova-sessione']",
    guideText: "Clicca '+ Nuova sessione' per creare un allenamento. Poi seleziona la sessione e tocca ogni giocatore per segnarlo presente o assente. Le presenze vengono salvate automaticamente.",
  },
  {
    id: 'convocazioni',
    title: 'Convocazioni',
    problem: 'Mandi ancora le convocazioni su WhatsApp e poi non sai chi ha confermato?',
    solution: 'ClubIS invia le convocazioni in-app e traccia le risposte di ogni giocatore.',
    route: '/dashboard/allenatore/convocazioni',
    targetSelector: "[data-onboarding='btn-nuova-convocazione']",
    guideText: "Clicca '+ Nuova convocazione', seleziona la partita e spunta i giocatori convocati. Ogni giocatore riceve una notifica e può confermare o declinare direttamente dall'app.",
  },
  {
    id: 'valutazioni',
    title: 'Valutazioni Tecniche',
    problem: 'Come dai un feedback strutturato ai tuoi giocatori sulla loro crescita tecnica?',
    solution: 'ClubIS ti permette di valutare ogni giocatore su 4 aree e condividere il voto con la famiglia.',
    route: '/dashboard/allenatore/valutazioni',
    targetSelector: "[data-onboarding='btn-nuova-valutazione']",
    guideText: 'Seleziona un giocatore e assegna un voto da 1 a 10 per tecnica, tattica, fisico e mentalità. Aggiungi una nota. Scegli se rendere la valutazione visibile alla famiglia.',
  },
  {
    id: 'tattica',
    title: 'Schema Tattico',
    problem: 'Disegni ancora i moduli di gioco su carta o su una lavagna che poi non rimane da nessuna parte?',
    solution: 'ClubIS ha un campo interattivo dove posizioni i giocatori con drag-and-drop e salvi la formazione.',
    route: '/dashboard/allenatore/tattica',
    targetSelector: "[data-onboarding='campo-tattico']",
    guideText: "Seleziona il modulo dal menu (4-3-3, 4-4-2, 3-5-2...) e trascina i giocatori nelle loro posizioni. Salva la formazione per usarla nelle convocazioni e nelle distinte.",
  },
  {
    id: 'statistiche',
    title: 'Statistiche Giocatori',
    problem: 'Sai sempre chi sono i giocatori più continui della stagione e chi sta calando di rendimento?',
    solution: 'ClubIS aggrega tutte le statistiche individuali in tempo reale per l\'intera stagione.',
    route: '/dashboard/allenatore/statistiche',
    targetSelector: "[data-onboarding='tabella-statistiche']",
    guideText: 'Qui vedi gol, assist, presenze, ammonizioni ed espulsioni di ogni giocatore. Ordina la tabella per qualsiasi colonna per trovare subito chi performa meglio.',
  },
]

const ONBOARDING_OSSERVATORE: OnboardingStep[] = [
  {
    id: 'nuovo-report',
    title: 'Report di Scouting',
    problem: 'I tuoi report di osservazione finiscono su carta o su note del telefono senza un formato standard?',
    solution: 'ClubIS ha un modulo strutturato per ogni osservazione, con voti, potenziale e export PDF immediato.',
    route: '/dashboard/osservatore/nuovo-report',
    targetSelector: "[data-onboarding='btn-nuovo-report']",
    guideText: "Clicca '+ Nuovo report' per iniziare un'osservazione. Inserisci nome del giocatore, club, data e luogo. Poi assegna i voti per area e scrivi punti di forza e debolezze.",
  },
  {
    id: 'export-pdf',
    title: 'Export PDF Report',
    problem: 'Come presenti un giocatore al DS in modo professionale senza perdere tempo a formattare un documento?',
    solution: 'ClubIS esporta il report in PDF professionale pronto per la presentazione in un click.',
    route: '/dashboard/osservatore/report',
    targetSelector: "[data-onboarding='btn-export-pdf']",
    guideText: "Apri un report già completato e clicca 'Esporta PDF'. Il documento è formattato con tutti i dati, i voti per area e le note. Pronto da inviare al DS o al presidente.",
  },
  {
    id: 'confronto',
    title: 'Confronto Giocatori',
    problem: 'Come decidi quale tra due giocatori osservati proporre al DS senza basarti solo sull\'intuito?',
    solution: 'ClubIS affianca i profili di due o più giocatori su ogni parametro valutato.',
    route: '/dashboard/osservatore/confronto',
    targetSelector: "[data-onboarding='btn-confronta']",
    guideText: 'Seleziona due giocatori dalla lista e clicca \'Confronta\'. Vedi tecnica, tattica, fisico e mentalità fianco a fianco. Le differenze sono evidenziate visivamente.',
  },
  {
    id: 'mappa',
    title: 'Mappa Osservazioni',
    problem: 'Sai da quali zone geografiche stai portando più segnalazioni? Stai coprendo il territorio in modo efficiente?',
    solution: 'ClubIS mostra sulla mappa dove si concentra la tua attività di scouting.',
    route: '/dashboard/osservatore/mappa',
    targetSelector: "[data-onboarding='mappa-scouting']",
    guideText: 'Questa mappa visualizza tutte le tue osservazioni geograficamente. Usa i filtri per vedere solo i giocatori in valutazione o quelli ingaggiati.',
  },
  {
    id: 'statistiche-personali',
    title: 'Le tue Statistiche',
    problem: 'Sai quanti giocatori hai segnalato e quanti sono stati effettivamente ingaggiati dal club?',
    solution: 'ClubIS monitora il tuo tasso di conversione e l\'impatto delle tue segnalazioni.',
    route: '/dashboard/osservatore/statistiche',
    targetSelector: "[data-onboarding='section-stats-osservatore']",
    guideText: 'Qui trovi il totale dei report creati, i giocatori ingaggiati grazie alle tue segnalazioni e il tasso di conversione. Una panoramica del tuo lavoro stagionale.',
  },
]

const ONBOARDING_FAMIGLIA: OnboardingStep[] = [
  {
    id: 'profilo-figlio',
    title: 'Profilo del Figlio',
    problem: 'Come tieni traccia delle informazioni sportive di tuo figlio senza chiamare il club ogni volta?',
    solution: 'ClubIS ti dà accesso al profilo completo di tuo figlio sempre aggiornato.',
    route: '/dashboard/famiglia',
    targetSelector: "[data-onboarding='card-profilo-figlio']",
    guideText: 'Qui trovi tutti i dati di tuo figlio: ruolo, età, tessera FIGC e foto. Le informazioni vengono aggiornate dalla segreteria.',
  },
  {
    id: 'presenze',
    title: 'Presenze agli Allenamenti',
    problem: 'Non sai mai con certezza quante volte tuo figlio ha partecipato agli allenamenti questo mese?',
    solution: 'ClubIS mostra la percentuale di presenze aggiornata in tempo reale.',
    route: '/dashboard/famiglia',
    targetSelector: "[data-onboarding='section-presenze-figlio']",
    guideText: 'Qui vedi la percentuale di presenze agli allenamenti degli ultimi 30 giorni. L\'indicatore diventa rosso se la partecipazione scende sotto la soglia.',
  },
  {
    id: 'valutazioni',
    title: 'Valutazioni del Coach',
    problem: 'Non ricevi mai un feedback strutturato dall\'allenatore sulla crescita di tuo figlio?',
    solution: 'ClubIS ti mostra le valutazioni tecniche condivise dall\'allenatore con voti per ogni area.',
    route: '/dashboard/famiglia',
    targetSelector: "[data-onboarding='section-valutazioni-figlio']",
    guideText: "Quando l'allenatore decide di condividere una valutazione, la trovi qui con i voti per tecnica, tattica, fisico e mentalità, più le note personali del coach.",
  },
  {
    id: 'pagamenti',
    title: 'Quote e Pagamenti',
    problem: 'Non sai mai esattamente quanto hai pagato e quanto devi ancora versare al club?',
    solution: 'ClubIS mostra la situazione aggiornata della quota con le rate future e le scadenze.',
    route: '/dashboard/famiglia/pagamenti',
    targetSelector: "[data-onboarding='section-pagamenti-figlio']",
    guideText: 'Qui vedi l\'importo totale, quanto è già stato pagato (con la barra di progresso) e le prossime rate con le relative scadenze. Riceverai un avviso prima di ogni scadenza.',
  },
  {
    id: 'calendario',
    title: 'Calendario',
    problem: 'Devi sempre chiedere al club o cercare su WhatsApp gli orari delle partite e degli allenamenti?',
    solution: 'ClubIS mostra il calendario completo della squadra di tuo figlio sempre aggiornato.',
    route: '/dashboard/famiglia/calendario',
    targetSelector: "[data-onboarding='sezione-calendario']",
    guideText: 'Qui trovi partite e allenamenti in ordine cronologico, con data, orario e luogo. Il calendario si aggiorna automaticamente quando il club fa modifiche.',
  },
]

export const ONBOARDING_STEPS: Record<string, OnboardingStep[]> = {
  segretario: ONBOARDING_SEGRETARIO,
  presidente: ONBOARDING_PRESIDENTE,
  direttore_sportivo: ONBOARDING_DS,
  allenatore: ONBOARDING_ALLENATORE,
  osservatore: ONBOARDING_OSSERVATORE,
  famiglia: ONBOARDING_FAMIGLIA,
}
